package emitter

import (
	"strings"

	appprepare "github.com/sipeed/picoclaw/pkg/appfactory/prepare"
)

// AppEntryEmitResult 表示 AppEntryEmitter 的输出。
type AppEntryEmitResult struct {
	Content  string
	FilePath string
}

// EmitAppEntry 从 DomainModel 和 PlanningContext 确定性生成 lib/main.dart。
// 返回 (result, true) 表示成功；(zero, false) 表示当前输入不在可 emit 范围内。
func EmitAppEntry(dm appprepare.DomainModel, pc appprepare.PlanningContext) (AppEntryEmitResult, bool) {
	templateID := strings.TrimSpace(pc.TemplateID)
	if templateID != "" && templateID != "flutter-open-lite" {
		return AppEntryEmitResult{}, false
	}
	profile := identifyCopyProfile(dm)
	var content string
	switch profile {
	case copyProfileProjectTaskTag:
		content = renderProjectTaskTagAppEntry()
	case copyProfileInventorySheetLineItem:
		content = renderInventoryAppEntry()
	default:
		return AppEntryEmitResult{}, false
	}
	return AppEntryEmitResult{
		Content:  content,
		FilePath: "lib/main.dart",
	}, true
}

func renderProjectTaskTagAppEntry() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import 'controllers/home_controller.dart';",
		"import 'controllers/record_form_controller.dart';",
		"import 'controllers/record_list_controller.dart';",
		"import 'models/project.dart';",
		"import 'models/tag.dart';",
		"import 'models/task.dart';",
		"import 'repositories/record_repository.dart';",
		"import 'template/open_lite_copy.dart';",
		"import 'views/record_detail_page.dart';",
		"import 'views/home_page.dart';",
		"import 'views/record_form_page.dart';",
		"import 'views/record_list_page.dart';",
		"",
		"Future<void> main() async {",
		"  WidgetsFlutterBinding.ensureInitialized();",
		"  final repository = HiveRecordRepository();",
		"  await repository.init();",
		"  runApp(AppFactoryApp(repository: repository));",
		"}",
		"",
		"class AppFactoryApp extends StatefulWidget {",
		"  const AppFactoryApp({super.key, required this.repository});",
		"",
		"  final RecordRepository repository;",
		"",
		"  @override",
		"  State<AppFactoryApp> createState() => _AppFactoryAppState();",
		"}",
		"",
		"class _AppFactoryAppState extends State<AppFactoryApp> {",
		"  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();",
		"  late final HomeController _homeController;",
		"  late final RecordListController _recordListController;",
		"  late final Future<void> _initialization;",
		"",
		"  @override",
		"  void initState() {",
		"    super.initState();",
		"    _homeController = HomeController(repository: widget.repository);",
		"    _recordListController = RecordListController(repository: widget.repository);",
		"    _initialization = _initializeControllers();",
		"  }",
		"",
		"  Future<void> _initializeControllers() async {",
		"    await _homeController.initialize();",
		"    await _recordListController.refresh();",
		"  }",
		"",
		"  @override",
		"  void dispose() {",
		"    _recordListController.dispose();",
		"    _homeController.dispose();",
		"    super.dispose();",
		"  }",
		"",
		"  Future<void> _refreshSurfaces() async {",
		"    await _homeController.refresh();",
		"    await _recordListController.refresh();",
		"  }",
		"",
		"  Future<List<Project>> _loadProjects() async {",
		"    return widget.repository.loadProjects();",
		"  }",
		"",
		"  Future<List<Tag>> _loadTags() async {",
		"    return widget.repository.loadTags();",
		"  }",
		"",
		"  Future<List<String>> _loadTaskTagIDs(String taskId) async {",
		"    final links = await widget.repository.loadTaskTagLinks();",
		"    return links",
		"        .where((link) => link.taskId == taskId)",
		"        .map((link) => link.tagId)",
		"        .toList(growable: false);",
		"  }",
		"",
		"  Future<void> _openTaskForm({Task? initialTask}) async {",
		"    final projects = await _loadProjects();",
		"    final tags = await _loadTags();",
		"    final initialTagIDs = initialTask == null",
		"        ? const <String>[]",
		"        : await _loadTaskTagIDs(initialTask.taskId);",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    final savedTask = await _navigatorKey.currentState!.push<Task>(",
		"      MaterialPageRoute<Task>(",
		"        builder: (_) => _OwnedRecordFormPage(",
		"          controller: RecordFormController(",
		"            repository: widget.repository,",
		"            projects: projects,",
		"            tags: tags,",
		"            initialTask: initialTask,",
		"            initialTagIds: initialTagIDs,",
		"          ),",
		"        ),",
		"      ),",
		"    );",
		"    if (savedTask != null) {",
		"      await _refreshSurfaces();",
		"    }",
		"  }",
		"",
		"  Future<void> _openCreateTask() async {",
		"    await _openTaskForm();",
		"  }",
		"",
		"  Future<void> _openEditTask(Task task) async {",
		"    await _openTaskForm(initialTask: task);",
		"  }",
		"",
		"  Future<void> _openTaskDetail(Task task) async {",
		"    final projects = await _loadProjects();",
		"    final tags = await _loadTags();",
		"    final taskTagIDs = await _loadTaskTagIDs(task.taskId);",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    await _navigatorKey.currentState!.push<void>(",
		"      MaterialPageRoute<void>(",
		"        builder: (_) => RecordDetailPage(",
		"          task: task,",
		"          projects: projects,",
		"          tags: tags,",
		"          taskTags: taskTagIDs,",
		"          onEdit: _openEditTask,",
		"        ),",
		"      ),",
		"    );",
		"    await _refreshSurfaces();",
		"  }",
		"",
		"  Future<void> _openTaskList() async {",
		"    await _recordListController.refresh();",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    await _navigatorKey.currentState!.push<void>(",
		"      MaterialPageRoute<void>(",
		"        builder: (_) => RecordListPage(",
		"          controller: _recordListController,",
		"          onCreateRecord: _openCreateTask,",
		"          onOpenTaskDetail: _openTaskDetail,",
		"        ),",
		"      ),",
		"    );",
		"    await _refreshSurfaces();",
		"  }",
		"",
		"  Future<void> _openViewAllTasks() async {",
		"    await _openTaskList();",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return MaterialApp(",
		"      navigatorKey: _navigatorKey,",
		"      title: openLiteCopy.appTitle,",
		"      theme: ThemeData(",
		"        colorScheme: ColorScheme.fromSeed(",
		"          seedColor: const Color(0xFF1565C0),",
		"          brightness: Brightness.light,",
		"        ),",
		"        scaffoldBackgroundColor: const Color(0xFFF4F7FB),",
		"        inputDecorationTheme: const InputDecorationTheme(",
		"          border: OutlineInputBorder(),",
		"        ),",
		"        useMaterial3: true,",
		"      ),",
		"      home: FutureBuilder<void>(",
		"        future: _initialization,",
		"        builder: (context, snapshot) {",
		"          if (snapshot.connectionState != ConnectionState.done) {",
		"            return const Scaffold(",
		"              body: Center(child: CircularProgressIndicator()),",
		"            );",
		"          }",
		"",
		"          return HomePage(",
		"            controller: _homeController,",
		"            onCreateTask: _openCreateTask,",
		"            onViewAllTasks: _openViewAllTasks,",
		"          );",
		"        },",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _OwnedRecordFormPage extends StatefulWidget {",
		"  const _OwnedRecordFormPage({required this.controller});",
		"",
		"  final RecordFormController controller;",
		"",
		"  @override",
		"  State<_OwnedRecordFormPage> createState() => _OwnedRecordFormPageState();",
		"}",
		"",
		"class _OwnedRecordFormPageState extends State<_OwnedRecordFormPage> {",
		"  @override",
		"  void dispose() {",
		"    widget.controller.dispose();",
		"    super.dispose();",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return RecordFormPage(controller: widget.controller);",
		"  }",
		"}",
	}, "\n") + "\n"
}

func renderInventoryAppEntry() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import 'controllers/home_controller.dart';",
		"import 'controllers/record_form_controller.dart';",
		"import 'controllers/record_list_controller.dart';",
		"import 'models/inventory_sheet.dart';",
		"import 'models/line_item.dart';",
		"import 'models/sku.dart';",
		"import 'models/warehouse.dart';",
		"import 'repositories/record_repository.dart';",
		"import 'template/open_lite_copy.dart';",
		"import 'views/home_page.dart';",
		"import 'views/record_detail_page.dart';",
		"import 'views/record_form_page.dart';",
		"import 'views/record_list_page.dart';",
		"",
		"Future<void> main() async {",
		"  WidgetsFlutterBinding.ensureInitialized();",
		"  final repository = HiveRecordRepository();",
		"  await repository.init();",
		"  runApp(AppFactoryApp(repository: repository));",
		"}",
		"",
		"class AppFactoryApp extends StatefulWidget {",
		"  const AppFactoryApp({super.key, required this.repository});",
		"",
		"  final RecordRepository repository;",
		"",
		"  @override",
		"  State<AppFactoryApp> createState() => _AppFactoryAppState();",
		"}",
		"",
		"class _AppFactoryAppState extends State<AppFactoryApp> {",
		"  final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();",
		"  late final HomeController _homeController;",
		"  late final RecordListController _listController;",
		"",
		"  @override",
		"  void initState() {",
		"    super.initState();",
		"    _homeController = HomeController(repository: widget.repository);",
		"    _listController = RecordListController(repository: widget.repository);",
		"    _homeController.initialize();",
		"  }",
		"",
		"  @override",
		"  void dispose() {",
		"    _homeController.dispose();",
		"    _listController.dispose();",
		"    super.dispose();",
		"  }",
		"",
		"  Future<void> _refreshSurfaces() async {",
		"    await _homeController.refresh();",
		"    await _listController.refresh();",
		"  }",
		"",
		"  Future<void> _ensureListDataLoaded() async {",
		"    if (_listController.warehouses.isNotEmpty || _listController.sheets.isNotEmpty) {",
		"      return;",
		"    }",
		"    await _listController.refresh();",
		"  }",
		"",
		"  Future<List<Warehouse>> _loadWarehouses() async {",
		"    final warehouses = await widget.repository.loadWarehouses();",
		"    if (warehouses.isNotEmpty) {",
		"      return warehouses;",
		"    }",
		"    return _listController.warehouses;",
		"  }",
		"",
		"  Future<List<Sku>> _loadSkus() async {",
		"    return widget.repository.loadSkus();",
		"  }",
		"",
		"  Future<List<LineItem>> _loadLineItemsForSheet(String sheetId) async {",
		"    final items = await widget.repository.loadLineItems();",
		"    return items.where((item) => item.sheetId == sheetId).toList(growable: false);",
		"  }",
		"",
		"  Future<void> _openCreateRecord() async {",
		"    await _ensureListDataLoaded();",
		"    final warehouses = await _loadWarehouses();",
		"    final skus = await _loadSkus();",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    final createdSheet = await _navigatorKey.currentState!.push<dynamic>(",
		"      MaterialPageRoute(",
		"        builder: (context) => _OwnedRecordFormPage(",
		"          controller: RecordFormController(",
		"            repository: widget.repository,",
		"            warehouses: warehouses,",
		"            skus: skus,",
		"          ),",
		"        ),",
		"      ),",
		"    );",
		"    if (createdSheet is InventorySheet) {",
		"      await _refreshSurfaces();",
		"    }",
		"  }",
		"",
		"  Future<void> _openEditRecord(InventorySheet sheet) async {",
		"    final warehouses = await _loadWarehouses();",
		"    final skus = await _loadSkus();",
		"    final items = await _loadLineItemsForSheet(sheet.sheetId);",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    final updatedSheet = await _navigatorKey.currentState!.push<dynamic>(",
		"      MaterialPageRoute(",
		"        builder: (context) => _OwnedRecordFormPage(",
		"          controller: RecordFormController(",
		"            repository: widget.repository,",
		"            warehouses: warehouses,",
		"            skus: skus,",
		"            initialSheet: sheet,",
		"            initialItems: items,",
		"          ),",
		"        ),",
		"      ),",
		"    );",
		"    if (updatedSheet is InventorySheet) {",
		"      await _refreshSurfaces();",
		"    }",
		"  }",
		"",
		"  Future<void> _openRecordDetail(InventorySheet sheet) async {",
		"    final items = await _loadLineItemsForSheet(sheet.sheetId);",
		"    final skus = await _loadSkus();",
		"    final warehouse = _listController.warehouseFor(sheet.warehouseId);",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    await _navigatorKey.currentState!.push<dynamic>(",
		"      MaterialPageRoute(",
		"        builder: (context) => RecordDetailPage(",
		"          sheet: sheet,",
		"          warehouse: warehouse,",
		"          items: items,",
		"          skus: skus,",
		"          onEdit: _openEditRecord,",
		"        ),",
		"      ),",
		"    );",
		"    await _refreshSurfaces();",
		"  }",
		"",
		"  Future<void> _openRecordList() async {",
		"    await _ensureListDataLoaded();",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    await _navigatorKey.currentState!.push<dynamic>(",
		"      MaterialPageRoute(",
		"        builder: (context) => RecordListPage(",
		"          controller: _listController,",
		"          onCreateRecord: _openCreateRecord,",
		"          onOpenRecordDetail: _openRecordDetail,",
		"        ),",
		"      ),",
		"    );",
		"    await _refreshSurfaces();",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return MaterialApp(",
		"      navigatorKey: _navigatorKey,",
		"      title: openLiteCopy.appTitle,",
		"      theme: ThemeData(",
		"        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1565C0)),",
		"        useMaterial3: true,",
		"      ),",
		"      home: HomePage(",
		"        controller: _homeController,",
		"        onCreateRecord: _openCreateRecord,",
		"        onViewAllRecords: _openRecordList,",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _OwnedRecordFormPage extends StatefulWidget {",
		"  const _OwnedRecordFormPage({required this.controller});",
		"",
		"  final RecordFormController controller;",
		"",
		"  @override",
		"  State<_OwnedRecordFormPage> createState() => _OwnedRecordFormPageState();",
		"}",
		"",
		"class _OwnedRecordFormPageState extends State<_OwnedRecordFormPage> {",
		"  @override",
		"  void dispose() {",
		"    widget.controller.dispose();",
		"    super.dispose();",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return RecordFormPage(controller: widget.controller);",
		"  }",
		"}",
	}, "\n") + "\n"
}
