package emitter

import (
	"strings"

	appprepare "github.com/sipeed/oneappfactory/pkg/appfactory/prepare"
)

// CollectionEmitResult 表示 CollectionEmitter 的输出。
type CollectionEmitResult struct {
	ListPageContent       string
	ListPagePath          string
	ListControllerContent string
	ListControllerPath    string
}

// EmitCollection 从 DomainModel 确定性生成 record_list_page.dart 和 record_list_controller.dart。
// 返回 (result, true) 表示成功；(zero, false) 表示当前 DomainModel 不在可 emit 范围内。
// 仅支持 relation-rich profile（project-task-tag、inventory-sheet-line-item），
// generic profile 的 NoFilter 函数依赖 workspace 文件系统推断类型，不属于纯 DomainModel 输入，返回 false。
func EmitCollection(dm appprepare.DomainModel) (CollectionEmitResult, bool) {
	profile := identifyCopyProfile(dm)
	switch profile {
	case copyProfileProjectTaskTag:
		return CollectionEmitResult{
			ListPageContent:       renderProjectTaskTagListPage(),
			ListPagePath:          "lib/views/record_list_page.dart",
			ListControllerContent: renderProjectTaskTagListController(),
			ListControllerPath:    "lib/controllers/record_list_controller.dart",
		}, true
	case copyProfileInventorySheetLineItem:
		return CollectionEmitResult{
			ListPageContent:       renderInventoryListPage(),
			ListPagePath:          "lib/views/record_list_page.dart",
			ListControllerContent: renderInventoryListController(),
			ListControllerPath:    "lib/controllers/record_list_controller.dart",
		}, true
	default:
		return CollectionEmitResult{}, false
	}
}

// renderProjectTaskTagListController 生成 project-task-tag profile 的 record_list_controller.dart。
func renderProjectTaskTagListController() string {
	return strings.Join([]string{
		"import 'package:flutter/foundation.dart' show ChangeNotifier, debugPrint;",
		"",
		"import '../models/project.dart';",
		"import '../models/tag.dart';",
		"import '../models/task.dart';",
		"import '../models/task_tag_link.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class RecordListController extends ChangeNotifier {",
		"  RecordListController({required RecordRepository repository})",
		"      : _repository = repository {",
		"    _refresh();",
		"  }",
		"",
		"  final RecordRepository _repository;",
		"  bool _isLoading = true;",
		"  List<Project> _projects = const [];",
		"  List<Task> _tasks = const [];",
		"  List<Tag> _tags = const [];",
		"  List<TaskTagLink> _links = const [];",
		"  String? _selectedProjectId;",
		"  String? _selectedTagId;",
		"  TaskStatus? _selectedStatus;",
		"",
		"  bool get isLoading => _isLoading;",
		"  List<Project> get projects => List.unmodifiable(_projects);",
		"  List<Task> get tasks => List.unmodifiable(_tasks);",
		"  List<Tag> get tags => List.unmodifiable(_tags);",
		"  String? get selectedProjectId => _selectedProjectId;",
		"  String? get selectedTagId => _selectedTagId;",
		"  TaskStatus? get selectedStatus => _selectedStatus;",
		"  bool get hasFilter => _selectedProjectId != null || _selectedTagId != null || _selectedStatus != null;",
		"",
		"  List<Task> get visibleTasks {",
		"    final taggedTaskIds = _selectedTagId == null",
		"        ? const <String>{}",
		"        : _links",
		"            .where((link) => link.tagId == _selectedTagId)",
		"            .map((link) => link.taskId)",
		"            .toSet();",
		"    return _tasks.where((task) {",
		"      if (_selectedProjectId != null && task.projectId != _selectedProjectId) {",
		"        return false;",
		"      }",
		"      if (_selectedTagId != null && !taggedTaskIds.contains(task.taskId)) {",
		"        return false;",
		"      }",
		"      if (_selectedStatus != null && task.status != _selectedStatus) {",
		"        return false;",
		"      }",
		"      return true;",
		"    }).toList(growable: false);",
		"  }",
		"",
		"  List<Task> get filteredTasks => visibleTasks;",
		"",
		"  void setProjectId(String? projectId) {",
		"    if (_selectedProjectId == projectId) {",
		"      return;",
		"    }",
		"    _selectedProjectId = projectId;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setTagId(String? tagId) {",
		"    if (_selectedTagId == tagId) {",
		"      return;",
		"    }",
		"    _selectedTagId = tagId;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setStatus(TaskStatus? status) {",
		"    if (_selectedStatus == status) {",
		"      return;",
		"    }",
		"    _selectedStatus = status;",
		"    notifyListeners();",
		"  }",
		"",
		"  void clearFilters() {",
		"    if (!hasFilter) {",
		"      return;",
		"    }",
		"    _selectedProjectId = null;",
		"    _selectedTagId = null;",
		"    _selectedStatus = null;",
		"    notifyListeners();",
		"  }",
		"",
		"  Future<void> refresh() async => _refresh();",
		"",
		"  Future<void> _refresh() async {",
		"    _isLoading = true;",
		"    notifyListeners();",
		"    try {",
		"      final projects = await _repository.loadProjects();",
		"      final tasks = await _repository.loadTasks();",
		"      final tags = await _repository.loadTags();",
		"      final links = await _repository.loadTaskTagLinks();",
		"      _projects = projects;",
		"      _tasks = tasks;",
		"      _tags = tags;",
		"      _links = links;",
		"    } catch (error) {",
		"      debugPrint('Error refreshing relation-rich task list: $error');",
		"    } finally {",
		"      _isLoading = false;",
		"      notifyListeners();",
		"    }",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryListController 生成 inventory profile 的 record_list_controller.dart。
func renderInventoryListController() string {
	return strings.Join([]string{
		"import 'package:flutter/foundation.dart' show ChangeNotifier, debugPrint;",
		"",
		"import '../models/inventory_sheet.dart';",
		"import '../models/line_item.dart';",
		"import '../models/sku.dart';",
		"import '../models/warehouse.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class RecordListController extends ChangeNotifier {",
		"  RecordListController({required RecordRepository repository})",
		"      : _repository = repository {",
		"    _refresh();",
		"  }",
		"",
		"  final RecordRepository _repository;",
		"  bool _isLoading = true;",
		"  List<InventorySheet> _sheets = const [];",
		"  List<LineItem> _lineItems = const [];",
		"  List<Sku> _skus = const [];",
		"  List<Warehouse> _warehouses = const [];",
		"  String? _selectedWarehouseId;",
		"  InventorySheetStatus? _selectedStatus;",
		"  bool _lowStockOnly = false;",
		"",
		"  bool get isLoading => _isLoading;",
		"  List<InventorySheet> get sheets => List.unmodifiable(_sheets);",
		"  List<Warehouse> get warehouses => List.unmodifiable(_warehouses);",
		"  String? get selectedWarehouseId => _selectedWarehouseId;",
		"  InventorySheetStatus? get selectedStatus => _selectedStatus;",
		"  bool get lowStockOnly => _lowStockOnly;",
		"  bool get hasFilter => (_selectedWarehouseId != null && _selectedWarehouseId!.isNotEmpty) || _selectedStatus != null || _lowStockOnly;",
		"",
		"  List<InventorySheet> get visibleSheets {",
		"    return _sheets.where((sheet) {",
		"      if (_selectedWarehouseId != null && sheet.warehouseId != _selectedWarehouseId) {",
		"        return false;",
		"      }",
		"      if (_selectedStatus != null && sheet.status != _selectedStatus) {",
		"        return false;",
		"      }",
		"      if (_lowStockOnly && !isLowStockSheet(sheet)) {",
		"        return false;",
		"      }",
		"      return true;",
		"    }).toList(growable: false);",
		"  }",
		"",
		"  List<InventorySheet> get filteredSheets => visibleSheets;",
		"",
		"  void setWarehouseId(String? warehouseId) {",
		"    final normalized = warehouseId?.trim();",
		"    final nextWarehouseId = normalized == null || normalized.isEmpty ? null : normalized;",
		"    if (_selectedWarehouseId == nextWarehouseId) {",
		"      return;",
		"    }",
		"    _selectedWarehouseId = nextWarehouseId;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setStatus(InventorySheetStatus? status) {",
		"    if (_selectedStatus == status) {",
		"      return;",
		"    }",
		"    _selectedStatus = status;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setLowStockOnly(bool value) {",
		"    if (_lowStockOnly == value) {",
		"      return;",
		"    }",
		"    _lowStockOnly = value;",
		"    notifyListeners();",
		"  }",
		"",
		"  void clearFilters() {",
		"    if (!hasFilter) {",
		"      return;",
		"    }",
		"    _selectedWarehouseId = null;",
		"    _selectedStatus = null;",
		"    _lowStockOnly = false;",
		"    notifyListeners();",
		"  }",
		"",
		"  Warehouse? warehouseFor(String warehouseId) {",
		"    for (final warehouse in _warehouses) {",
		"      if (warehouse.warehouseId == warehouseId) {",
		"        return warehouse;",
		"      }",
		"    }",
		"    return null;",
		"  }",
		"",
		"  List<LineItem> lineItemsForSheet(String sheetId) {",
		"    return _lineItems.where((item) => item.sheetId == sheetId).toList(growable: false);",
		"  }",
		"",
		"  bool isLowStockSheet(InventorySheet sheet) {",
		"    final skuById = <String, Sku>{for (final sku in _skus) sku.skuId: sku};",
		"    for (final item in _lineItems) {",
		"      if (item.sheetId != sheet.sheetId) {",
		"        continue;",
		"      }",
		"      final sku = skuById[item.skuId];",
		"      if (sku != null && item.countedQty <= sku.reorderThreshold) {",
		"        return true;",
		"      }",
		"    }",
		"    return false;",
		"  }",
		"",
		"  Future<void> refresh() async => _refresh();",
		"",
		"  Future<void> _refresh() async {",
		"    _isLoading = true;",
		"    notifyListeners();",
		"    try {",
		"      final sheets = await _repository.loadInventorySheets();",
		"      final lineItems = await _repository.loadLineItems();",
		"      final skus = await _repository.loadSkus();",
		"      final warehouses = await _repository.loadWarehouses();",
		"      _sheets = sheets;",
		"      _lineItems = lineItems;",
		"      _skus = skus;",
		"      _warehouses = warehouses;",
		"    } catch (error) {",
		"      debugPrint('Failed to refresh inventory list: $error');",
		"      _sheets = const [];",
		"      _lineItems = const [];",
		"      _skus = const [];",
		"      _warehouses = const [];",
		"    } finally {",
		"      _isLoading = false;",
		"      notifyListeners();",
		"    }",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderProjectTaskTagListPage 生成 project-task-tag profile 的 record_list_page.dart。
func renderProjectTaskTagListPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/record_list_controller.dart';",
		"import '../models/project.dart';",
		"import '../models/task.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordListPage extends StatelessWidget {",
		"  const RecordListPage({",
		"    super.key,",
		"    required this.controller,",
		"    required this.onCreateRecord,",
		"    required this.onOpenTaskDetail,",
		"  });",
		"",
		"  final RecordListController controller;",
		"  final Future<void> Function() onCreateRecord;",
		"  final Future<void> Function(Task task) onOpenTaskDetail;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: controller,",
		"      builder: (context, _) {",
		"        final tasks = controller.visibleTasks;",
		"        return Scaffold(",
		"          appBar: AppBar(",
		"            title: Text(openLiteCopy.listPageTitle),",
		"            actions: [",
		"              if (controller.hasFilter)",
		"                IconButton(",
		"                  onPressed: controller.clearFilters,",
		"                  tooltip: openLiteCopy.clearFilterActionLabel,",
		"                  icon: const Icon(Icons.filter_alt_off),",
		"                ),",
		"            ],",
		"          ),",
		"          body: Column(",
		"            crossAxisAlignment: CrossAxisAlignment.start,",
		"            children: [",
		"              Padding(",
		"                padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),",
		"                child: Text(",
		"                  openLiteCopy.listFilterTitle,",
		"                  style: Theme.of(context).textTheme.titleMedium,",
		"                ),",
		"              ),",
		"              _RelationRichFilterStrip(controller: controller),",
		"              Padding(",
		"                padding: const EdgeInsets.fromLTRB(16, 8, 16, 12),",
		"                child: Text(openLiteCopy.listCountLabel(tasks.length)),",
		"              ),",
		"              Expanded(",
		"                child: controller.isLoading",
		"                    ? const Center(child: CircularProgressIndicator())",
		"                    : tasks.isEmpty",
		"                        ? _EmptyState(hasFilter: controller.hasFilter)",
		"                        : ListView.separated(",
		"                            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),",
		"                            itemCount: tasks.length,",
		"                            separatorBuilder: (_, __) => const SizedBox(height: 12),",
		"                            itemBuilder: (context, index) {",
		"                              final task = tasks[index];",
		"                              return _TaskCard(",
		"                                task: task,",
		"                                projectTitle: _projectTitleFor(controller.projects, task.projectId),",
		"                                onTap: () {",
		"                                  onOpenTaskDetail(task);",
		"                                },",
		"                              );",
		"                            },",
		"                          ),",
		"              ),",
		"            ],",
		"          ),",
		"          floatingActionButton: FloatingActionButton.extended(",
		"            onPressed: () => onCreateRecord(),",
		"            icon: const Icon(Icons.add),",
		"            label: Text(openLiteCopy.createPrimaryActionLabel),",
		"          ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"",
		"  static String _projectTitleFor(List<Project> projects, String projectId) {",
		"    for (final project in projects) {",
		"      if (project.projectId == projectId) {",
		"        return project.title;",
		"      }",
		"    }",
		"    return projectId;",
		"  }",
		"}",
		"",
		"class _RelationRichFilterStrip extends StatelessWidget {",
		"  const _RelationRichFilterStrip({required this.controller});",
		"",
		"  final RecordListController controller;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return SingleChildScrollView(",
		"      padding: const EdgeInsets.symmetric(horizontal: 16),",
		"      scrollDirection: Axis.horizontal,",
		"      child: Wrap(",
		"        spacing: 8,",
		"        runSpacing: 8,",
		"        children: [",
		"          ChoiceChip(",
		"            label: Text(openLiteCopy.allFilterLabel),",
		"            selected: controller.selectedProjectId == null && controller.selectedTagId == null && controller.selectedStatus == null,",
		"            onSelected: (_) => controller.clearFilters(),",
		"          ),",
		"          ...controller.projects.map((project) => ChoiceChip(",
		"                label: Text(project.title),",
		"                selected: controller.selectedProjectId == project.projectId,",
		"                onSelected: (selected) => controller.setProjectId(selected ? project.projectId : null),",
		"              )),",
		"          ...controller.tags.map((tag) => ChoiceChip(",
		"                label: Text('#${tag.name}'),",
		"                selected: controller.selectedTagId == tag.tagId,",
		"                onSelected: (selected) => controller.setTagId(selected ? tag.tagId : null),",
		"              )),",
		"          ...TaskStatus.values.map((status) => ChoiceChip(",
		"                label: Text(openLiteCopy.taskStatusLabel(status)),",
		"                selected: controller.selectedStatus == status,",
		"                onSelected: (selected) => controller.setStatus(selected ? status : null),",
		"              )),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _TaskCard extends StatelessWidget {",
		"  const _TaskCard({",
		"    required this.task,",
		"    required this.projectTitle,",
		"    required this.onTap,",
		"  });",
		"",
		"  final Task task;",
		"  final String projectTitle;",
		"  final VoidCallback onTap;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final dueText = task.dueOn == null",
		"        ? openLiteCopy.detailDateLabel",
		"        : '${task.dueOn!.year}-${task.dueOn!.month.toString().padLeft(2, '0')}-${task.dueOn!.day.toString().padLeft(2, '0')}';",
		"    return Card(",
		"      child: ListTile(",
		"        onTap: onTap,",
		"        title: Text(task.title),",
		"        subtitle: Text('$projectTitle · ${openLiteCopy.taskStatusLabel(task.status)} · $dueText'),",
		"        trailing: const Icon(Icons.chevron_right),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _EmptyState extends StatelessWidget {",
		"  const _EmptyState({required this.hasFilter});",
		"",
		"  final bool hasFilter;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Center(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(24),",
		"        child: Column(",
		"          mainAxisSize: MainAxisSize.min,",
		"          children: [",
		"            Text(hasFilter ? openLiteCopy.filteredEmptyTitle : openLiteCopy.listEmptyLabel),",
		"            if (hasFilter) ...[",
		"              const SizedBox(height: 8),",
		"              Text(openLiteCopy.filteredEmptyDescription),",
		"            ],",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryListPage 生成 inventory profile 的 record_list_page.dart。
func renderInventoryListPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/record_list_controller.dart';",
		"import '../models/inventory_sheet.dart';",
		"import '../models/warehouse.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordListPage extends StatelessWidget {",
		"  const RecordListPage({",
		"    super.key,",
		"    required this.controller,",
		"    required this.onCreateRecord,",
		"    required this.onOpenRecordDetail,",
		"  });",
		"",
		"  final RecordListController controller;",
		"  final Future<void> Function() onCreateRecord;",
		"  final Future<void> Function(InventorySheet sheet) onOpenRecordDetail;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: controller,",
		"      builder: (context, _) {",
		"        final sheets = controller.visibleSheets;",
		"        return Scaffold(",
		"          appBar: AppBar(",
		"            title: Text(openLiteCopy.listPageTitle),",
		"            actions: [",
		"              if (controller.hasFilter)",
		"                IconButton(",
		"                  onPressed: controller.clearFilters,",
		"                  tooltip: openLiteCopy.clearFilterActionLabel,",
		"                  icon: const Icon(Icons.filter_alt_off),",
		"                ),",
		"            ],",
		"          ),",
		"          body: Column(",
		"            crossAxisAlignment: CrossAxisAlignment.start,",
		"            children: [",
		"              Padding(",
		"                padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),",
		"                child: Text(",
		"                  openLiteCopy.listFilterTitle,",
		"                  style: Theme.of(context).textTheme.titleMedium,",
		"                ),",
		"              ),",
		"              _InventoryFilterStrip(controller: controller),",
		"              Padding(",
		"                padding: const EdgeInsets.fromLTRB(16, 8, 16, 12),",
		"                child: Text(openLiteCopy.listCountLabel(sheets.length)),",
		"              ),",
		"              Expanded(",
		"                child: controller.isLoading",
		"                    ? const Center(child: CircularProgressIndicator())",
		"                    : controller.sheets.isEmpty",
		"                        ? const _EmptyState(hasFilter: false)",
		"                        : sheets.isEmpty",
		"                            ? const _EmptyState(hasFilter: true)",
		"                            : ListView.separated(",
		"                                padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),",
		"                                itemCount: sheets.length,",
		"                                separatorBuilder: (_, __) => const SizedBox(height: 12),",
		"                                itemBuilder: (context, index) {",
		"                                  final sheet = sheets[index];",
		"                                  final warehouse = controller.warehouseFor(sheet.warehouseId);",
		"                                  final itemCount = controller.lineItemsForSheet(sheet.sheetId).length;",
		"                                  return _InventorySheetCard(",
		"                                    sheet: sheet,",
		"                                    warehouse: warehouse,",
		"                                    itemCount: itemCount,",
		"                                    lowStock: controller.isLowStockSheet(sheet),",
		"                                    onTap: () => onOpenRecordDetail(sheet),",
		"                                  );",
		"                                },",
		"                              ),",
		"              ),",
		"            ],",
		"          ),",
		"          floatingActionButton: FloatingActionButton.extended(",
		"            onPressed: () => onCreateRecord(),",
		"            icon: const Icon(Icons.add),",
		"            label: Text(openLiteCopy.createPrimaryActionLabel),",
		"          ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"}",
		"",
		"class _InventoryFilterStrip extends StatelessWidget {",
		"  const _InventoryFilterStrip({required this.controller});",
		"",
		"  final RecordListController controller;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return SingleChildScrollView(",
		"      padding: const EdgeInsets.symmetric(horizontal: 16),",
		"      scrollDirection: Axis.horizontal,",
		"      child: Wrap(",
		"        spacing: 8,",
		"        runSpacing: 8,",
		"        children: [",
		"          ChoiceChip(",
		"            label: Text(openLiteCopy.allFilterLabel),",
		"            selected: !controller.hasFilter,",
		"            onSelected: (_) => controller.clearFilters(),",
		"          ),",
		"          ...controller.warehouses.map((warehouse) => ChoiceChip(",
		"                label: Text(warehouse.name),",
		"                selected: controller.selectedWarehouseId == warehouse.warehouseId,",
		"                onSelected: (selected) => controller.setWarehouseId(selected ? warehouse.warehouseId : null),",
		"              )),",
		"          ...InventorySheetStatus.values.map((status) => ChoiceChip(",
		"                label: Text(openLiteCopy.statusLabel(status)),",
		"                selected: controller.selectedStatus == status,",
		"                onSelected: (selected) => controller.setStatus(selected ? status : null),",
		"              )),",
		"          FilterChip(",
		"            label: const Text('低库存'),",
		"            selected: controller.lowStockOnly,",
		"            onSelected: controller.setLowStockOnly,",
		"          ),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _InventorySheetCard extends StatelessWidget {",
		"  const _InventorySheetCard({",
		"    required this.sheet,",
		"    required this.warehouse,",
		"    required this.itemCount,",
		"    required this.lowStock,",
		"    required this.onTap,",
		"  });",
		"",
		"  final InventorySheet sheet;",
		"  final Warehouse? warehouse;",
		"  final int itemCount;",
		"  final bool lowStock;",
		"  final VoidCallback onTap;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final warehouseTitle = warehouse?.name ?? sheet.warehouseId;",
		"    return Card(",
		"      child: ListTile(",
		"        onTap: onTap,",
		"        title: Text(warehouseTitle),",
		"        subtitle: Text('${openLiteCopy.statusLabel(sheet.status)} · ${_formatInventorySheetDate(sheet.countedOn)} · $itemCount 项'),",
		"        trailing: lowStock",
		"            ? const Icon(Icons.warning_amber_rounded, color: Colors.orange)",
		"            : const Icon(Icons.chevron_right),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _EmptyState extends StatelessWidget {",
		"  const _EmptyState({required this.hasFilter});",
		"",
		"  final bool hasFilter;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Center(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(24),",
		"        child: Column(",
		"          mainAxisSize: MainAxisSize.min,",
		"          children: [",
		"            Text(hasFilter ? openLiteCopy.filteredEmptyTitle : openLiteCopy.listEmptyLabel),",
		"            if (hasFilter) ...[",
		"              const SizedBox(height: 8),",
		"              Text(openLiteCopy.filteredEmptyDescription),",
		"            ],",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"String _formatInventorySheetDate(DateTime value) {",
		"  final month = value.month.toString().padLeft(2, '0');",
		"  final day = value.day.toString().padLeft(2, '0');",
		"  return '${value.year}-$month-$day';",
		"}",
	}, "\n") + "\n"
}
