package emitter

import (
	"strings"

	appprepare "github.com/sipeed/picoclaw/pkg/appfactory/prepare"
)

// InspectionEmitResult 表示 InspectionEmitter 的输出。
type InspectionEmitResult struct {
	DetailPageContent string
	DetailPagePath    string
}

// EmitInspection 从 DomainModel 确定性生成 record_detail_page.dart。
// 返回 (result, true) 表示成功；(zero, false) 表示当前 DomainModel 不在可 emit 范围内。
// 仅支持 relation-rich profile（project-task-tag、inventory-sheet-line-item），
// generic profile 无全量 canonical 模板，返回 false。
func EmitInspection(dm appprepare.DomainModel) (InspectionEmitResult, bool) {
	profile := identifyCopyProfile(dm)
	switch profile {
	case copyProfileProjectTaskTag:
		return InspectionEmitResult{
			DetailPageContent: renderProjectTaskTagDetailPage(),
			DetailPagePath:    "lib/views/record_detail_page.dart",
		}, true
	case copyProfileInventorySheetLineItem:
		return InspectionEmitResult{
			DetailPageContent: renderInventoryDetailPage(),
			DetailPagePath:    "lib/views/record_detail_page.dart",
		}, true
	default:
		return InspectionEmitResult{}, false
	}
}

// renderProjectTaskTagDetailPage 生成 project-task-tag profile 的 record_detail_page.dart。
func renderProjectTaskTagDetailPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../models/project.dart';",
		"import '../models/tag.dart';",
		"import '../models/task.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordDetailPage extends StatefulWidget {",
		"  const RecordDetailPage({",
		"    super.key,",
		"    required this.task,",
		"    required this.projects,",
		"    required this.tags,",
		"    required this.taskTags,",
		"    required this.onEdit,",
		"  });",
		"",
		"  final Task task;",
		"  final List<Project> projects;",
		"  final List<Tag> tags;",
		"  final List<String> taskTags;",
		"  final Future<void> Function(Task task) onEdit;",
		"",
		"  @override",
		"  State<RecordDetailPage> createState() => _RecordDetailPageState();",
		"}",
		"",
		"class _RecordDetailPageState extends State<RecordDetailPage> {",
		"  late Task _task;",
		"",
		"  @override",
		"  void initState() {",
		"    super.initState();",
		"    _task = widget.task;",
		"  }",
		"",
		"  Future<void> _editTask() async {",
		"    await widget.onEdit(_task);",
		"    if (!mounted) {",
		"      return;",
		"    }",
		"    setState(() {});",
		"  }",
		"",
		"  String _projectTitleFor(String projectId) {",
		"    for (final project in widget.projects) {",
		"      if (project.projectId == projectId) {",
		"        return project.title;",
		"      }",
		"    }",
		"    return projectId;",
		"  }",
		"",
		"  List<Tag> _selectedTags() {",
		"    final taskTagIds = widget.taskTags.toSet();",
		"    return widget.tags.where((tag) => taskTagIds.contains(tag.tagId)).toList(growable: false);",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final selectedTags = _selectedTags();",
		"    return Scaffold(",
		"      appBar: AppBar(",
		"        title: Text(openLiteCopy.detailPageTitle),",
		"        actions: [",
		"          TextButton(",
		"            onPressed: _editTask,",
		"            child: Text(openLiteCopy.editActionLabel),",
		"          ),",
		"        ],",
		"      ),",
		"      body: ListView(",
		"        padding: const EdgeInsets.all(20),",
		"        children: [",
		"          _DetailCard(",
		"            title: _task.title,",
		"            subtitle: openLiteCopy.taskStatusLabel(_task.status),",
		"          ),",
		"          const SizedBox(height: 16),",
		"          _InfoTile(",
		"            label: openLiteCopy.detailProjectLabel,",
		"            value: _projectTitleFor(_task.projectId),",
		"          ),",
		"          _InfoTile(",
		"            label: openLiteCopy.detailStatusLabel,",
		"            value: openLiteCopy.taskStatusLabel(_task.status),",
		"          ),",
		"          if (selectedTags.isNotEmpty)",
		"            _InfoTile(",
		"              label: openLiteCopy.tagFilterLabel,",
		"              value: selectedTags.map((tag) => tag.name).join(', '),",
		"            ),",
		"          if (_task.dueOn != null)",
		"            _InfoTile(",
		"              label: openLiteCopy.detailDateLabel,",
		"              value: _formatDate(_task.dueOn!),",
		"            ),",
		"          _InfoTile(",
		"            label: openLiteCopy.detailNoteLabel,",
		"            value: (_task.note ?? '').trim().isEmpty ? openLiteCopy.emptyNoteLabel : _task.note!.trim(),",
		"            multiline: true,",
		"          ),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"",
		"  String _formatDate(DateTime date) {",
		"    return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';",
		"  }",
		"}",
		"",
		"class _DetailCard extends StatelessWidget {",
		"  const _DetailCard({required this.title, required this.subtitle});",
		"",
		"  final String title;",
		"  final String subtitle;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.all(20),",
		"      decoration: BoxDecoration(",
		"        borderRadius: BorderRadius.circular(24),",
		"        color: const Color(0xFF1565C0),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(",
		"            title,",
		"            style: const TextStyle(",
		"              color: Colors.white,",
		"              fontSize: 24,",
		"              fontWeight: FontWeight.w700,",
		"            ),",
		"          ),",
		"          const SizedBox(height: 8),",
		"          Text(",
		"            subtitle,",
		"            style: const TextStyle(color: Colors.white70),",
		"          ),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _InfoTile extends StatelessWidget {",
		"  const _InfoTile({",
		"    required this.label,",
		"    required this.value,",
		"    this.multiline = false,",
		"  });",
		"",
		"  final String label;",
		"  final String value;",
		"  final bool multiline;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      margin: const EdgeInsets.only(bottom: 12),",
		"      padding: const EdgeInsets.all(16),",
		"      decoration: BoxDecoration(",
		"        color: Colors.white,",
		"        borderRadius: BorderRadius.circular(18),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(label, style: Theme.of(context).textTheme.labelMedium),",
		"          const SizedBox(height: 6),",
		"          Text(",
		"            value,",
		"            style: TextStyle(height: multiline ? 1.4 : 1.2),",
		"          ),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryDetailPage 生成 inventory profile 的 record_detail_page.dart。
func renderInventoryDetailPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../models/inventory_sheet.dart';",
		"import '../models/line_item.dart';",
		"import '../models/sku.dart';",
		"import '../models/warehouse.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordDetailPage extends StatelessWidget {",
		"  const RecordDetailPage({",
		"    super.key,",
		"    required this.sheet,",
		"    required this.warehouse,",
		"    required this.items,",
		"    required this.skus,",
		"    required this.onEdit,",
		"  });",
		"",
		"  final InventorySheet sheet;",
		"  final Warehouse? warehouse;",
		"  final List<LineItem> items;",
		"  final List<Sku> skus;",
		"  final Future<void> Function(InventorySheet sheet) onEdit;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final warehouseTitle = warehouse?.name ?? sheet.warehouseId;",
		"    final warehouseLocation = warehouse?.location?.trim() ?? '';",
		"    return Scaffold(",
		"      appBar: AppBar(",
		"        title: Text(openLiteCopy.detailPageTitle),",
		"        actions: [",
		"          TextButton(",
		"            onPressed: () => onEdit(sheet),",
		"            child: Text(openLiteCopy.editActionLabel),",
		"          ),",
		"        ],",
		"      ),",
		"      body: ListView(",
		"        padding: const EdgeInsets.all(20),",
		"        children: [",
		"          _HeaderCard(",
		"            warehouseTitle: warehouseTitle,",
		"            statusLabel: openLiteCopy.statusLabel(sheet.status),",
		"          ),",
		"          const SizedBox(height: 16),",
		"          _InfoTile(label: openLiteCopy.detailCategoryLabel, value: warehouseTitle),",
		"          if (warehouseLocation.isNotEmpty)",
		"            _InfoTile(label: openLiteCopy.warehouseLocationLabel, value: warehouseLocation),",
		"          _InfoTile(label: openLiteCopy.detailStatusLabel, value: openLiteCopy.statusLabel(sheet.status)),",
		"          _InfoTile(label: openLiteCopy.detailDateLabel, value: _formatInventoryDetailDate(sheet.countedOn)),",
		"          _InfoTile(",
		"            label: openLiteCopy.detailNoteLabel,",
		"            value: (sheet.note ?? '').trim().isEmpty ? openLiteCopy.emptyNoteLabel : sheet.note!.trim(),",
		"            multiline: true,",
		"          ),",
		"          const SizedBox(height: 8),",
		"          Text(openLiteCopy.lineItemTitle, style: Theme.of(context).textTheme.titleMedium),",
		"          const SizedBox(height: 12),",
		"          if (items.isEmpty)",
		"            const _EmptyLineItemState()",
		"          else",
		"            ...items.map((item) => Padding(",
		"                  padding: const EdgeInsets.only(bottom: 12),",
		"                  child: _LineItemCard(",
		"                    item: item,",
		"                    skuName: _skuNameFor(item.skuId),",
		"                  ),",
		"                )),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"",
		"  String _skuNameFor(String skuId) {",
		"    for (final sku in skus) {",
		"      if (sku.skuId == skuId) {",
		"        return sku.name;",
		"      }",
		"    }",
		"    return skuId;",
		"  }",
		"}",
		"",
		"class _HeaderCard extends StatelessWidget {",
		"  const _HeaderCard({required this.warehouseTitle, required this.statusLabel});",
		"",
		"  final String warehouseTitle;",
		"  final String statusLabel;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.all(20),",
		"      decoration: BoxDecoration(",
		"        borderRadius: BorderRadius.circular(24),",
		"        color: const Color(0xFF1565C0),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(",
		"            warehouseTitle,",
		"            style: const TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.w700),",
		"          ),",
		"          const SizedBox(height: 8),",
		"          Text(statusLabel, style: const TextStyle(color: Colors.white70)),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _InfoTile extends StatelessWidget {",
		"  const _InfoTile({required this.label, required this.value, this.multiline = false});",
		"",
		"  final String label;",
		"  final String value;",
		"  final bool multiline;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      margin: const EdgeInsets.only(bottom: 12),",
		"      padding: const EdgeInsets.all(16),",
		"      decoration: BoxDecoration(",
		"        color: Colors.white,",
		"        borderRadius: BorderRadius.circular(18),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(label, style: Theme.of(context).textTheme.labelMedium),",
		"          const SizedBox(height: 6),",
		"          Text(value, style: TextStyle(height: multiline ? 1.4 : 1.2)),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _LineItemCard extends StatelessWidget {",
		"  const _LineItemCard({required this.item, required this.skuName});",
		"",
		"  final LineItem item;",
		"  final String skuName;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(16),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            Text(skuName, style: Theme.of(context).textTheme.titleSmall),",
		"            const SizedBox(height: 8),",
		"            Text('${openLiteCopy.expectedQtyLabel}：${item.expectedQty}'),",
		"            Text('${openLiteCopy.countedQtyLabel}：${item.countedQty}'),",
		"            Text('${openLiteCopy.varianceQtyLabel}：${item.varianceQty}'),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _EmptyLineItemState extends StatelessWidget {",
		"  const _EmptyLineItemState();",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.all(20),",
		"      decoration: BoxDecoration(",
		"        color: Theme.of(context).colorScheme.surfaceContainerHighest,",
		"        borderRadius: BorderRadius.circular(18),",
		"      ),",
		"      child: const Text('当前库存单还没有明细项。'),",
		"    );",
		"  }",
		"}",
		"",
		"String _formatInventoryDetailDate(DateTime value) {",
		"  final month = value.month.toString().padLeft(2, '0');",
		"  final day = value.day.toString().padLeft(2, '0');",
		"  return '${value.year}-$month-$day';",
		"}",
	}, "\n") + "\n"
}
