package emitter

import (
	"strings"

	appprepare "github.com/sipeed/oneappfactory/pkg/appfactory/prepare"
)

// MutationEmitResult 表示 MutationEmitter 的输出。
type MutationEmitResult struct {
	FormPageContent       string
	FormPagePath          string
	FormControllerContent string
	FormControllerPath    string
}

// EmitMutation 从 DomainModel 确定性生成 record_form_page.dart 和 record_form_controller.dart。
// 返回 (result, true) 表示成功；(zero, false) 表示当前 DomainModel 不在可 emit 范围内。
// 仅支持 relation-rich profile（project-task-tag、inventory-sheet-line-item），
// generic profile 的 Repository-driven 函数依赖 workspace 文件系统推断类型，不属于纯 DomainModel 输入，返回 false。
func EmitMutation(dm appprepare.DomainModel) (MutationEmitResult, bool) {
	profile := identifyCopyProfile(dm)
	switch profile {
	case copyProfileProjectTaskTag:
		return MutationEmitResult{
			FormPageContent:       renderProjectTaskTagFormPage(),
			FormPagePath:          "lib/views/record_form_page.dart",
			FormControllerContent: renderProjectTaskTagFormController(),
			FormControllerPath:    "lib/controllers/record_form_controller.dart",
		}, true
	case copyProfileInventorySheetLineItem:
		return MutationEmitResult{
			FormPageContent:       renderInventoryFormPage(),
			FormPagePath:          "lib/views/record_form_page.dart",
			FormControllerContent: renderInventoryFormController(),
			FormControllerPath:    "lib/controllers/record_form_controller.dart",
		}, true
	default:
		return MutationEmitResult{}, false
	}
}

// renderProjectTaskTagFormController 生成 project-task-tag profile 的 record_form_controller.dart。
func renderProjectTaskTagFormController() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../models/project.dart';",
		"import '../models/tag.dart';",
		"import '../models/task.dart';",
		"import '../models/task_tag_link.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class RecordFormController extends ChangeNotifier {",
		"  RecordFormController({",
		"    required this.repository,",
		"    this.projects = const [],",
		"    this.tags = const [],",
		"    Task? initialTask,",
		"    List<String>? initialTagIds,",
		"  })  : titleController = TextEditingController(text: initialTask?.title ?? ''),",
		"        noteController = TextEditingController(text: initialTask?.note ?? ''),",
		"        projectController = TextEditingController(",
		"          text: initialTask?.projectId ?? (projects.isNotEmpty ? projects.first.projectId : ''),",
		"        ),",
		"        _initialTask = initialTask,",
		"        _selectedStatus = initialTask?.status ?? TaskStatus.todo,",
		"        _selectedDate = initialTask?.dueOn,",
		"        _selectedTagIds = <String>{...(initialTagIds ?? const <String>[])};",
		"",
		"  final RecordRepository repository;",
		"  final List<Project> projects;",
		"  final List<Tag> tags;",
		"  final TextEditingController titleController;",
		"  final TextEditingController noteController;",
		"  final TextEditingController projectController;",
		"  final Task? _initialTask;",
		"  final Set<String> _selectedTagIds;",
		"",
		"  TaskStatus _selectedStatus;",
		"  DateTime? _selectedDate;",
		"",
		"  bool get isEditing => _initialTask != null;",
		"  TaskStatus get selectedStatus => _selectedStatus;",
		"  DateTime? get selectedDate => _selectedDate;",
		"  List<String> get selectedTagIds => _selectedTagIds.toList(growable: false);",
		"",
		"  void setStatus(TaskStatus status) {",
		"    if (_selectedStatus == status) {",
		"      return;",
		"    }",
		"    _selectedStatus = status;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setDate(DateTime? date) {",
		"    _selectedDate = date;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setProject(String projectId) {",
		"    if (projectController.text == projectId) {",
		"      return;",
		"    }",
		"    projectController.text = projectId;",
		"    notifyListeners();",
		"  }",
		"",
		"  void toggleTag(String tagId) {",
		"    if (_selectedTagIds.contains(tagId)) {",
		"      _selectedTagIds.remove(tagId);",
		"    } else {",
		"      _selectedTagIds.add(tagId);",
		"    }",
		"    notifyListeners();",
		"  }",
		"",
		"  Future<Task> submit() async {",
		"    final title = titleController.text.trim();",
		"    final projectId = projectController.text.trim();",
		"    if (title.isEmpty) {",
		"      throw const FormatException('请输入任务标题');",
		"    }",
		"    if (projectId.isEmpty) {",
		"      throw const FormatException('请选择所属项目');",
		"    }",
		"",
		"    final taskId = _initialTask?.taskId ?? DateTime.now().microsecondsSinceEpoch.toString();",
		"    final task = Task(",
		"      taskId: taskId,",
		"      projectId: projectId,",
		"      title: title,",
		"      status: _selectedStatus,",
		"      dueOn: _selectedDate,",
		"      note: noteController.text.trim().isEmpty ? null : noteController.text.trim(),",
		"    );",
		"",
		"    final nextTasks = (await repository.loadTasks())",
		"        .where((item) => item.taskId != taskId)",
		"        .toList(growable: true)",
		"      ..add(task);",
		"    await repository.saveTasks(nextTasks);",
		"",
		"    final nextLinks = (await repository.loadTaskTagLinks())",
		"        .where((link) => link.taskId != taskId)",
		"        .toList(growable: true)",
		"      ..addAll(",
		"        _selectedTagIds.map(",
		"          (tagId) => TaskTagLink(",
		"            linkId: '${taskId}_$tagId',",
		"            taskId: taskId,",
		"            tagId: tagId,",
		"          ),",
		"        ),",
		"      );",
		"    await repository.saveTaskTagLinks(nextLinks);",
		"    return task;",
		"  }",
		"",
		"  @override",
		"  void dispose() {",
		"    titleController.dispose();",
		"    noteController.dispose();",
		"    projectController.dispose();",
		"    super.dispose();",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryFormController 生成 inventory profile 的 record_form_controller.dart。
func renderInventoryFormController() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../models/inventory_sheet.dart';",
		"import '../models/line_item.dart';",
		"import '../models/sku.dart';",
		"import '../models/warehouse.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class RecordFormController extends ChangeNotifier {",
		"  RecordFormController({",
		"    required this.repository,",
		"    List<Warehouse> warehouses = const [],",
		"    List<Sku> skus = const [],",
		"    InventorySheet? initialSheet,",
		"    List<LineItem>? initialItems,",
		"  })  : _warehouses = List<Warehouse>.of(warehouses),",
		"        _skus = List<Sku>.of(skus),",
		"        warehouseController = TextEditingController(",
		"          text: initialSheet?.warehouseId ?? (warehouses.isNotEmpty ? warehouses.first.warehouseId : ''),",
		"        ),",
		"        countedOnController = TextEditingController(",
		"          text: _formatInventoryDate(initialSheet?.countedOn ?? DateTime.now()),",
		"        ),",
		"        noteController = TextEditingController(text: initialSheet?.note ?? ''),",
		"        _initialSheet = initialSheet,",
		"        _lineItems = List<LineItem>.of(initialItems ?? const <LineItem>[]),",
		"        _selectedStatus = initialSheet?.status ?? InventorySheetStatus.draft;",
		"",
		"  final RecordRepository repository;",
		"  final List<Warehouse> _warehouses;",
		"  final List<Sku> _skus;",
		"  final TextEditingController warehouseController;",
		"  final TextEditingController countedOnController;",
		"  final TextEditingController noteController;",
		"  final InventorySheet? _initialSheet;",
		"  final List<LineItem> _lineItems;",
		"",
		"  InventorySheetStatus _selectedStatus;",
		"  int _nextDraftSeed = 0;",
		"",
		"  bool get isEditing => _initialSheet != null;",
		"  List<Warehouse> get warehouses => List.unmodifiable(_warehouses);",
		"  List<Sku> get skus => List.unmodifiable(_skus);",
		"  InventorySheetStatus get selectedStatus => _selectedStatus;",
		"  DateTime get selectedCountedOn => DateTime.tryParse(countedOnController.text.trim()) ?? DateTime.now();",
		"  List<LineItem> get lineItems => List.unmodifiable(_lineItems);",
		"",
		"  void setStatus(InventorySheetStatus status) {",
		"    if (_selectedStatus == status) {",
		"      return;",
		"    }",
		"    _selectedStatus = status;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setWarehouse(String warehouseId) {",
		"    if (warehouseController.text == warehouseId) {",
		"      return;",
		"    }",
		"    warehouseController.text = warehouseId;",
		"    notifyListeners();",
		"  }",
		"",
		"  void setCountedOn(DateTime value) {",
		"    countedOnController.text = _formatInventoryDate(value);",
		"    notifyListeners();",
		"  }",
		"",
		"  void addLineItem({String? skuId, int expectedQty = 0, int countedQty = 0}) {",
		"    final resolvedSkuId = skuId ?? (_skus.isNotEmpty ? _skus.first.skuId : '');",
		"    _lineItems.add(",
		"      LineItem(",
		"        lineItemId: _nextGeneratedId('line'),",
		"        sheetId: _initialSheet?.sheetId ?? '',",
		"        skuId: resolvedSkuId,",
		"        expectedQty: expectedQty,",
		"        countedQty: countedQty,",
		"        varianceQty: countedQty - expectedQty,",
		"      ),",
		"    );",
		"    notifyListeners();",
		"  }",
		"",
		"  void updateLineItem(String lineItemId, {String? skuId, int? expectedQty, int? countedQty}) {",
		"    final index = _lineItems.indexWhere((item) => item.lineItemId == lineItemId);",
		"    if (index < 0) {",
		"      return;",
		"    }",
		"    final current = _lineItems[index];",
		"    final nextExpectedQty = expectedQty ?? current.expectedQty;",
		"    final nextCountedQty = countedQty ?? current.countedQty;",
		"    _lineItems[index] = LineItem(",
		"      lineItemId: current.lineItemId,",
		"      sheetId: current.sheetId,",
		"      skuId: skuId ?? current.skuId,",
		"      expectedQty: nextExpectedQty,",
		"      countedQty: nextCountedQty,",
		"      varianceQty: nextCountedQty - nextExpectedQty,",
		"    );",
		"    notifyListeners();",
		"  }",
		"",
		"  void removeLineItem(String lineItemId) {",
		"    _lineItems.removeWhere((item) => item.lineItemId == lineItemId);",
		"    notifyListeners();",
		"  }",
		"",
		"  Future<InventorySheet> submit() async {",
		"    final warehouseId = warehouseController.text.trim();",
		"    if (warehouseId.isEmpty) {",
		"      throw const FormatException('请选择所属仓库');",
		"    }",
		"    if (_lineItems.isEmpty) {",
		"      throw const FormatException('请至少添加一个明细项');",
		"    }",
		"",
		"    final sheetId = _initialSheet?.sheetId ?? _nextGeneratedId('sheet');",
		"    final note = noteController.text.trim();",
		"    final sheet = InventorySheet(",
		"      sheetId: sheetId,",
		"      warehouseId: warehouseId,",
		"      status: _selectedStatus,",
		"      countedOn: selectedCountedOn,",
		"      note: note.isEmpty ? null : note,",
		"    );",
		"",
		"    if (isEditing) {",
		"      await repository.updateInventorySheet(sheet);",
		"    } else {",
		"      await repository.addInventorySheet(sheet);",
		"    }",
		"",
		"    final nextItems = (await repository.loadLineItems())",
		"        .where((item) => item.sheetId != sheetId)",
		"        .toList(growable: true)",
		"      ..addAll(",
		"        _lineItems.map((item) {",
		"          final resolvedLineItemId = item.lineItemId.trim().isEmpty ? _nextGeneratedId('line') : item.lineItemId;",
		"          final expectedQty = item.expectedQty;",
		"          final countedQty = item.countedQty;",
		"          return LineItem(",
		"            lineItemId: resolvedLineItemId,",
		"            sheetId: sheetId,",
		"            skuId: item.skuId,",
		"            expectedQty: expectedQty,",
		"            countedQty: countedQty,",
		"            varianceQty: countedQty - expectedQty,",
		"          );",
		"        }),",
		"      );",
		"    await repository.saveLineItems(nextItems);",
		"    return sheet;",
		"  }",
		"",
		"  String _nextGeneratedId(String prefix) {",
		"    final seed = DateTime.now().microsecondsSinceEpoch + _nextDraftSeed;",
		"    _nextDraftSeed += 1;",
		"    return '$prefix-$seed';",
		"  }",
		"",
		"  @override",
		"  void dispose() {",
		"    warehouseController.dispose();",
		"    countedOnController.dispose();",
		"    noteController.dispose();",
		"    super.dispose();",
		"  }",
		"}",
		"",
		"String _formatInventoryDate(DateTime value) {",
		"  final month = value.month.toString().padLeft(2, '0');",
		"  final day = value.day.toString().padLeft(2, '0');",
		"  return '${value.year}-$month-$day';",
		"}",
	}, "\n") + "\n"
}

// renderProjectTaskTagFormPage 生成 project-task-tag profile 的 record_form_page.dart。
func renderProjectTaskTagFormPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/record_form_controller.dart';",
		"import '../models/task.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordFormPage extends StatefulWidget {",
		"  const RecordFormPage({",
		"    super.key,",
		"    required this.controller,",
		"  });",
		"",
		"  final RecordFormController controller;",
		"",
		"  @override",
		"  State<RecordFormPage> createState() => _RecordFormPageState();",
		"}",
		"",
		"class _RecordFormPageState extends State<RecordFormPage> {",
		"  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();",
		"",
		"  Future<void> _pickDate() async {",
		"    final pickedDate = await showDatePicker(",
		"      context: context,",
		"      initialDate: widget.controller.selectedDate ?? DateTime.now(),",
		"      firstDate: DateTime(2020),",
		"      lastDate: DateTime(2100),",
		"    );",
		"    if (pickedDate != null) {",
		"      widget.controller.setDate(pickedDate);",
		"    }",
		"  }",
		"",
		"  Future<void> _save() async {",
		"    if (!_formKey.currentState!.validate()) {",
		"      return;",
		"    }",
		"    try {",
		"      final savedTask = await widget.controller.submit();",
		"      if (!mounted) {",
		"        return;",
		"      }",
		"      Navigator.of(context).pop(savedTask);",
		"    } on FormatException catch (error) {",
		"      if (!mounted) {",
		"        return;",
		"      }",
		"      ScaffoldMessenger.of(context).showSnackBar(",
		"        SnackBar(content: Text(error.message)),",
		"      );",
		"    }",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: widget.controller,",
		"      builder: (context, _) {",
		"        return Scaffold(",
		"          appBar: AppBar(",
		"            title: Text(",
		"              widget.controller.isEditing ? openLiteCopy.editPageTitle : openLiteCopy.createPageTitle,",
		"            ),",
		"          ),",
		"          body: Form(",
		"            key: _formKey,",
		"            child: ListView(",
		"              padding: const EdgeInsets.all(20),",
		"              children: [",
		"                TextFormField(",
		"                  key: const Key('title-field'),",
		"                  controller: widget.controller.titleController,",
		"                  decoration: InputDecoration(",
		"                    labelText: openLiteCopy.titleFieldLabel,",
		"                  ),",
		"                  validator: (value) {",
		"                    if ((value ?? '').trim().isEmpty) {",
		"                      return openLiteCopy.titleFieldRequiredError;",
		"                    }",
		"                    return null;",
		"                  },",
		"                ),",
		"                const SizedBox(height: 16),",
		"                DropdownButtonFormField<String>(",
		"                  value: widget.controller.projectController.text.isEmpty ? null : widget.controller.projectController.text,",
		"                  items: widget.controller.projects",
		"                      .map(",
		"                        (project) => DropdownMenuItem<String>(",
		"                          value: project.projectId,",
		"                          child: Text(project.title),",
		"                        ),",
		"                      )",
		"                      .toList(),",
		"                  decoration: InputDecoration(",
		"                    labelText: openLiteCopy.projectFieldLabel,",
		"                  ),",
		"                  onChanged: (value) {",
		"                    if (value != null) {",
		"                      widget.controller.setProject(value);",
		"                    }",
		"                  },",
		"                ),",
		"                const SizedBox(height: 16),",
		"                Wrap(",
		"                  spacing: 8,",
		"                  children: widget.controller.tags.map((tag) {",
		"                    final isSelected = widget.controller.selectedTagIds.contains(tag.tagId);",
		"                    return FilterChip(",
		"                      label: Text(tag.name),",
		"                      selected: isSelected,",
		"                      onSelected: (_) => widget.controller.toggleTag(tag.tagId),",
		"                    );",
		"                  }).toList(),",
		"                ),",
		"                const SizedBox(height: 16),",
		"                Wrap(",
		"                  spacing: 8,",
		"                  runSpacing: 8,",
		"                  children: [",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.todoFilterLabel),",
		"                      selected: widget.controller.selectedStatus == TaskStatus.todo,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(TaskStatus.todo);",
		"                        }",
		"                      },",
		"                    ),",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.doingFilterLabel),",
		"                      selected: widget.controller.selectedStatus == TaskStatus.doing,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(TaskStatus.doing);",
		"                        }",
		"                      },",
		"                    ),",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.doneFilterLabel),",
		"                      selected: widget.controller.selectedStatus == TaskStatus.done,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(TaskStatus.done);",
		"                        }",
		"                      },",
		"                    ),",
		"                  ],",
		"                ),",
		"                const SizedBox(height: 16),",
		"                ListTile(",
		"                  contentPadding: const EdgeInsets.symmetric(horizontal: 12),",
		"                  shape: RoundedRectangleBorder(",
		"                    borderRadius: BorderRadius.circular(12),",
		"                    side: BorderSide(color: Theme.of(context).dividerColor),",
		"                  ),",
		"                  title: Text(openLiteCopy.dateFieldLabel),",
		"                  subtitle: Text(",
		"                    widget.controller.selectedDate != null",
		"                        ? '${widget.controller.selectedDate!.year}-${widget.controller.selectedDate!.month.toString().padLeft(2, '0')}-${widget.controller.selectedDate!.day.toString().padLeft(2, '0')}'",
		"                        : '请选择日期',",
		"                  ),",
		"                  trailing: IconButton(",
		"                    onPressed: _pickDate,",
		"                    icon: const Icon(Icons.calendar_today),",
		"                  ),",
		"                ),",
		"                const SizedBox(height: 16),",
		"                TextFormField(",
		"                  key: const Key('note-field'),",
		"                  controller: widget.controller.noteController,",
		"                  decoration: InputDecoration(",
		"                    labelText: openLiteCopy.noteFieldLabel,",
		"                    hintText: openLiteCopy.noteFieldHint,",
		"                  ),",
		"                  minLines: 2,",
		"                  maxLines: 3,",
		"                ),",
		"                const SizedBox(height: 24),",
		"                FilledButton(",
		"                  onPressed: _save,",
		"                  child: Text(",
		"                    widget.controller.isEditing ? openLiteCopy.editSubmitLabel : openLiteCopy.createSubmitLabel,",
		"                  ),",
		"                ),",
		"              ],",
		"            ),",
		"          ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryFormPage 生成 inventory profile 的 record_form_page.dart。
func renderInventoryFormPage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/record_form_controller.dart';",
		"import '../models/inventory_sheet.dart';",
		"import '../models/line_item.dart';",
		"import '../models/sku.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class RecordFormPage extends StatefulWidget {",
		"  const RecordFormPage({",
		"    super.key,",
		"    required this.controller,",
		"  });",
		"",
		"  final RecordFormController controller;",
		"",
		"  @override",
		"  State<RecordFormPage> createState() => _RecordFormPageState();",
		"}",
		"",
		"class _RecordFormPageState extends State<RecordFormPage> {",
		"  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();",
		"",
		"  Future<void> _pickDate() async {",
		"    final pickedDate = await showDatePicker(",
		"      context: context,",
		"      initialDate: widget.controller.selectedCountedOn,",
		"      firstDate: DateTime(2020),",
		"      lastDate: DateTime(2100),",
		"    );",
		"    if (pickedDate != null) {",
		"      widget.controller.setCountedOn(pickedDate);",
		"    }",
		"  }",
		"",
		"  Future<void> _save() async {",
		"    if (!_formKey.currentState!.validate()) {",
		"      return;",
		"    }",
		"    try {",
		"      final savedSheet = await widget.controller.submit();",
		"      if (!mounted) {",
		"        return;",
		"      }",
		"      Navigator.of(context).pop(savedSheet);",
		"    } on FormatException catch (error) {",
		"      if (!mounted) {",
		"        return;",
		"      }",
		"      ScaffoldMessenger.of(context).showSnackBar(",
		"        SnackBar(content: Text(error.message)),",
		"      );",
		"    }",
		"  }",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: widget.controller,",
		"      builder: (context, _) {",
		"        final warehouseValue = widget.controller.warehouses.any(",
		"              (warehouse) => warehouse.warehouseId == widget.controller.warehouseController.text.trim(),",
		"            )",
		"            ? widget.controller.warehouseController.text.trim()",
		"            : null;",
		"        return Scaffold(",
		"          appBar: AppBar(",
		"            title: Text(",
		"              widget.controller.isEditing ? openLiteCopy.editPageTitle : openLiteCopy.createPageTitle,",
		"            ),",
		"          ),",
		"          body: Form(",
		"            key: _formKey,",
		"            child: ListView(",
		"              padding: const EdgeInsets.all(20),",
		"              children: [",
		"                DropdownButtonFormField<String>(",
		"                  value: warehouseValue,",
		"                  decoration: InputDecoration(labelText: openLiteCopy.categoryFieldLabel),",
		"                  items: widget.controller.warehouses",
		"                      .map(",
		"                        (warehouse) => DropdownMenuItem<String>(",
		"                          value: warehouse.warehouseId,",
		"                          child: Text(warehouse.name),",
		"                        ),",
		"                      )",
		"                      .toList(),",
		"                  onChanged: (value) {",
		"                    if (value != null) {",
		"                      widget.controller.setWarehouse(value);",
		"                    }",
		"                  },",
		"                ),",
		"                const SizedBox(height: 16),",
		"                Wrap(",
		"                  spacing: 8,",
		"                  runSpacing: 8,",
		"                  children: [",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.inboxFilterLabel),",
		"                      selected: widget.controller.selectedStatus == InventorySheetStatus.draft,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(InventorySheetStatus.draft);",
		"                        }",
		"                      },",
		"                    ),",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.inProgressFilterLabel),",
		"                      selected: widget.controller.selectedStatus == InventorySheetStatus.checking,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(InventorySheetStatus.checking);",
		"                        }",
		"                      },",
		"                    ),",
		"                    ChoiceChip(",
		"                      label: Text(openLiteCopy.doneFilterLabel),",
		"                      selected: widget.controller.selectedStatus == InventorySheetStatus.closed,",
		"                      onSelected: (selected) {",
		"                        if (selected) {",
		"                          widget.controller.setStatus(InventorySheetStatus.closed);",
		"                        }",
		"                      },",
		"                    ),",
		"                  ],",
		"                ),",
		"                const SizedBox(height: 16),",
		"                ListTile(",
		"                  contentPadding: const EdgeInsets.symmetric(horizontal: 12),",
		"                  shape: RoundedRectangleBorder(",
		"                    borderRadius: BorderRadius.circular(12),",
		"                    side: BorderSide(color: Theme.of(context).dividerColor),",
		"                  ),",
		"                  title: Text(openLiteCopy.dateFieldLabel),",
		"                  subtitle: Text(_formatInventoryDate(widget.controller.selectedCountedOn)),",
		"                  trailing: IconButton(",
		"                    onPressed: _pickDate,",
		"                    icon: const Icon(Icons.calendar_today),",
		"                  ),",
		"                ),",
		"                const SizedBox(height: 16),",
		"                TextFormField(",
		"                  key: const Key('note-field'),",
		"                  controller: widget.controller.noteController,",
		"                  decoration: InputDecoration(",
		"                    labelText: openLiteCopy.noteFieldLabel,",
		"                    hintText: openLiteCopy.noteFieldHint,",
		"                  ),",
		"                  minLines: 2,",
		"                  maxLines: 3,",
		"                ),",
		"                const SizedBox(height: 24),",
		"                Text(",
		"                  openLiteCopy.lineItemTitle,",
		"                  style: Theme.of(context).textTheme.titleMedium,",
		"                ),",
		"                const SizedBox(height: 12),",
		"                if (widget.controller.lineItems.isEmpty)",
		"                  const _LineItemEmptyState()",
		"                else",
		"                  ...widget.controller.lineItems.map((item) => Padding(",
		"                        padding: const EdgeInsets.only(bottom: 12),",
		"                        child: _LineItemEditor(",
		"                          item: item,",
		"                          skus: widget.controller.skus,",
		"                          onSkuChanged: (value) {",
		"                            if (value != null) {",
		"                              widget.controller.updateLineItem(item.lineItemId, skuId: value);",
		"                            }",
		"                          },",
		"                          onExpectedQtyChanged: (value) => widget.controller.updateLineItem(item.lineItemId, expectedQty: int.tryParse(value) ?? 0),",
		"                          onCountedQtyChanged: (value) => widget.controller.updateLineItem(item.lineItemId, countedQty: int.tryParse(value) ?? 0),",
		"                          onRemove: () => widget.controller.removeLineItem(item.lineItemId),",
		"                        ),",
		"                      )),",
		"                const SizedBox(height: 12),",
		"                OutlinedButton.icon(",
		"                  key: const Key('add-line-item-button'),",
		"                  onPressed: () => widget.controller.addLineItem(),",
		"                  icon: const Icon(Icons.add),",
		"                  label: const Text('添加明细项'),",
		"                ),",
		"                const SizedBox(height: 24),",
		"                FilledButton(",
		"                  onPressed: _save,",
		"                  child: Text(",
		"                    widget.controller.isEditing ? openLiteCopy.editSubmitLabel : openLiteCopy.createSubmitLabel,",
		"                  ),",
		"                ),",
		"              ],",
		"            ),",
		"          ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"}",
		"",
		"class _LineItemEditor extends StatelessWidget {",
		"  const _LineItemEditor({",
		"    required this.item,",
		"    required this.skus,",
		"    required this.onSkuChanged,",
		"    required this.onExpectedQtyChanged,",
		"    required this.onCountedQtyChanged,",
		"    required this.onRemove,",
		"  });",
		"",
		"  final LineItem item;",
		"  final List<Sku> skus;",
		"  final ValueChanged<String?> onSkuChanged;",
		"  final ValueChanged<String> onExpectedQtyChanged;",
		"  final ValueChanged<String> onCountedQtyChanged;",
		"  final VoidCallback onRemove;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final selectedSkuId = skus.any((sku) => sku.skuId == item.skuId) ? item.skuId : null;",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(16),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            DropdownButtonFormField<String>(",
		"              value: selectedSkuId,",
		"              decoration: InputDecoration(labelText: openLiteCopy.skuLabel),",
		"              items: skus",
		"                  .map(",
		"                    (sku) => DropdownMenuItem<String>(",
		"                      value: sku.skuId,",
		"                      child: Text(sku.name),",
		"                    ),",
		"                  )",
		"                  .toList(),",
		"              onChanged: onSkuChanged,",
		"            ),",
		"            const SizedBox(height: 12),",
		"            Row(",
		"              children: [",
		"                Expanded(",
		"                  child: TextFormField(",
		"                    key: ValueKey('expected-${item.lineItemId}-${item.expectedQty}'),",
		"                    initialValue: item.expectedQty.toString(),",
		"                    decoration: InputDecoration(labelText: openLiteCopy.expectedQtyLabel),",
		"                    keyboardType: TextInputType.number,",
		"                    onChanged: onExpectedQtyChanged,",
		"                  ),",
		"                ),",
		"                const SizedBox(width: 12),",
		"                Expanded(",
		"                  child: TextFormField(",
		"                    key: ValueKey('counted-${item.lineItemId}-${item.countedQty}'),",
		"                    initialValue: item.countedQty.toString(),",
		"                    decoration: InputDecoration(labelText: openLiteCopy.countedQtyLabel),",
		"                    keyboardType: TextInputType.number,",
		"                    onChanged: onCountedQtyChanged,",
		"                  ),",
		"                ),",
		"              ],",
		"            ),",
		"            const SizedBox(height: 12),",
		"            Row(",
		"              children: [",
		"                Expanded(child: Text('${openLiteCopy.varianceQtyLabel}：${item.varianceQty}')),",
		"                IconButton(onPressed: onRemove, icon: const Icon(Icons.delete_outline)),",
		"              ],",
		"            ),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _LineItemEmptyState extends StatelessWidget {",
		"  const _LineItemEmptyState();",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.all(20),",
		"      decoration: BoxDecoration(",
		"        color: Theme.of(context).colorScheme.surfaceContainerHighest,",
		"        borderRadius: BorderRadius.circular(18),",
		"      ),",
		"      child: const Text('先添加至少一个盘点明细项。'),",
		"    );",
		"  }",
		"}",
		"",
		"String _formatInventoryDate(DateTime value) {",
		"  final month = value.month.toString().padLeft(2, '0');",
		"  final day = value.day.toString().padLeft(2, '0');",
		"  return '${value.year}-$month-$day';",
		"}",
	}, "\n") + "\n"
}
