package emitter

import (
	"strings"

	appprepare "github.com/sipeed/picoclaw/pkg/appfactory/prepare"
)

// OverviewEmitResult 表示 OverviewEmitter 的输出。
type OverviewEmitResult struct {
	HomePageContent       string
	HomePagePath          string
	HomeControllerContent string
	HomeControllerPath    string
}

// EmitOverview 从 DomainModel 确定性生成 home_page.dart 和 home_controller.dart。
// 返回 (result, true) 表示成功；(zero, false) 表示当前 DomainModel 不在可 emit 范围内。
// 仅支持 relation-rich profile（project-task-tag、inventory-sheet-line-item），
// generic profile 无全量 canonical 模板，返回 false。
func EmitOverview(dm appprepare.DomainModel) (OverviewEmitResult, bool) {
	profile := identifyCopyProfile(dm)
	switch profile {
	case copyProfileProjectTaskTag:
		return OverviewEmitResult{
			HomePageContent:       renderProjectTaskTagHomePage(),
			HomePagePath:          "lib/views/home_page.dart",
			HomeControllerContent: renderProjectTaskTagHomeController(),
			HomeControllerPath:    "lib/controllers/home_controller.dart",
		}, true
	case copyProfileInventorySheetLineItem:
		return OverviewEmitResult{
			HomePageContent:       renderInventoryHomePage(),
			HomePagePath:          "lib/views/home_page.dart",
			HomeControllerContent: renderInventoryHomeController(),
			HomeControllerPath:    "lib/controllers/home_controller.dart",
		}, true
	default:
		return OverviewEmitResult{}, false
	}
}

// renderProjectTaskTagHomePage 生成 project-task-tag profile 的 home_page.dart。
func renderProjectTaskTagHomePage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/home_controller.dart';",
		"import '../models/dashboard_summary.dart';",
		"import '../models/project.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class HomePage extends StatelessWidget {",
		"  const HomePage({",
		"    super.key,",
		"    required this.controller,",
		"    required this.onCreateTask,",
		"    required this.onViewAllTasks,",
		"  });",
		"",
		"  final HomeController controller;",
		"  final Future<void> Function() onCreateTask;",
		"  final Future<void> Function() onViewAllTasks;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: controller,",
		"      builder: (context, _) {",
		"        return Scaffold(",
		"          appBar: AppBar(title: Text(openLiteCopy.appTitle)),",
		"          body: controller.isLoading",
		"              ? const Center(child: CircularProgressIndicator())",
		"              : ListView(",
		"                  padding: const EdgeInsets.all(20),",
		"                  children: [",
		"                    _OverviewActions(",
		"                      onCreateTask: () {",
		"                        onCreateTask();",
		"                      },",
		"                      onViewAllTasks: () {",
		"                        onViewAllTasks();",
		"                      },",
		"                    ),",
		"                    const SizedBox(height: 20),",
		"                    Text(",
		"                      openLiteCopy.homeSummaryTitle,",
		"                      style: Theme.of(context).textTheme.titleLarge,",
		"                    ),",
		"                    const SizedBox(height: 12),",
		"                    if (controller.projects.isEmpty)",
		"                      _OverviewEmptyState()",
		"                    else",
		"                      ...controller.projects.map((project) => Padding(",
		"                            padding: const EdgeInsets.only(bottom: 12),",
		"                            child: _ProjectSummaryCard(",
		"                              project: project,",
		"                              summary: controller.getSummaryForProject(project.projectId),",
		"                            ),",
		"                          )),",
		"                  ],",
		"                ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"}",
		"",
		"class _OverviewActions extends StatelessWidget {",
		"  const _OverviewActions({",
		"    required this.onCreateTask,",
		"    required this.onViewAllTasks,",
		"  });",
		"",
		"  final VoidCallback onCreateTask;",
		"  final VoidCallback onViewAllTasks;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Row(",
		"      children: [",
		"        Expanded(",
		"          child: FilledButton(",
		"            onPressed: onCreateTask,",
		"            child: Text(openLiteCopy.createPrimaryActionLabel),",
		"          ),",
		"        ),",
		"        const SizedBox(width: 12),",
		"        Expanded(",
		"          child: OutlinedButton(",
		"            onPressed: onViewAllTasks,",
		"            child: Text(openLiteCopy.viewAllActionLabel),",
		"          ),",
		"        ),",
		"      ],",
		"    );",
		"  }",
		"}",
		"",
		"class _ProjectSummaryCard extends StatelessWidget {",
		"  const _ProjectSummaryCard({required this.project, required this.summary});",
		"",
		"  final Project project;",
		"  final DashboardSummary? summary;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final data = summary;",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(16),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            Text(project.title, style: Theme.of(context).textTheme.titleMedium),",
		"            const SizedBox(height: 12),",
		"            Wrap(",
		"              spacing: 12,",
		"              runSpacing: 12,",
		"              children: [",
		"                _SummaryStat(label: openLiteCopy.todoFilterLabel, value: '${data?.openTaskCount ?? 0}'),",
		"                _SummaryStat(label: openLiteCopy.doneFilterLabel, value: '${data?.doneTaskCount ?? 0}'),",
		"                _SummaryStat(label: openLiteCopy.tagFilterLabel, value: '${data?.taggedTaskCount ?? 0}'),",
		"              ],",
		"            ),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _SummaryStat extends StatelessWidget {",
		"  const _SummaryStat({required this.label, required this.value});",
		"",
		"  final String label;",
		"  final String value;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),",
		"      decoration: BoxDecoration(",
		"        color: Theme.of(context).colorScheme.surfaceContainerHighest,",
		"        borderRadius: BorderRadius.circular(16),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(label),",
		"          const SizedBox(height: 4),",
		"          Text(value, style: Theme.of(context).textTheme.titleMedium),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _OverviewEmptyState extends StatelessWidget {",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(24),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            Text(openLiteCopy.homeEmptyTitle, style: Theme.of(context).textTheme.titleMedium),",
		"            const SizedBox(height: 8),",
		"            Text(openLiteCopy.homeEmptyDescription),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryHomePage 生成 inventory-sheet-line-item profile 的 home_page.dart。
func renderInventoryHomePage() string {
	return strings.Join([]string{
		"import 'package:flutter/material.dart';",
		"",
		"import '../controllers/home_controller.dart';",
		"import '../models/dashboard_summary.dart';",
		"import '../models/warehouse.dart';",
		"import '../template/open_lite_copy.dart';",
		"",
		"class HomePage extends StatelessWidget {",
		"  const HomePage({",
		"    super.key,",
		"    required this.controller,",
		"    required this.onCreateRecord,",
		"    required this.onViewAllRecords,",
		"  });",
		"",
		"  final HomeController controller;",
		"  final Future<void> Function() onCreateRecord;",
		"  final Future<void> Function() onViewAllRecords;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return AnimatedBuilder(",
		"      animation: controller,",
		"      builder: (context, _) {",
		"        return Scaffold(",
		"          appBar: AppBar(title: Text(openLiteCopy.appTitle)),",
		"          body: controller.isLoading",
		"              ? const Center(child: CircularProgressIndicator())",
		"              : ListView(",
		"                  padding: const EdgeInsets.all(20),",
		"                  children: [",
		"                    _OverviewHero(controller: controller),",
		"                    const SizedBox(height: 20),",
		"                    _OverviewActions(",
		"                      onCreateRecord: () {",
		"                        onCreateRecord();",
		"                      },",
		"                      onViewAllRecords: () {",
		"                        onViewAllRecords();",
		"                      },",
		"                    ),",
		"                    const SizedBox(height: 20),",
		"                    Text(",
		"                      openLiteCopy.recentRecordsTitle,",
		"                      style: Theme.of(context).textTheme.titleLarge,",
		"                    ),",
		"                    const SizedBox(height: 12),",
		"                    if (controller.warehouses.isEmpty)",
		"                      const _OverviewEmptyState()",
		"                    else",
		"                      ...controller.warehouses.map((warehouse) => Padding(",
		"                            padding: const EdgeInsets.only(bottom: 12),",
		"                            child: _WarehouseSummaryCard(",
		"                              warehouse: warehouse,",
		"                              summary: controller.getSummaryForWarehouse(warehouse.warehouseId),",
		"                            ),",
		"                          )),",
		"                  ],",
		"                ),",
		"        );",
		"      },",
		"    );",
		"  }",
		"}",
		"",
		"class _OverviewHero extends StatelessWidget {",
		"  const _OverviewHero({required this.controller});",
		"",
		"  final HomeController controller;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.all(20),",
		"      decoration: BoxDecoration(",
		"        color: const Color(0xFF1565C0),",
		"        borderRadius: BorderRadius.circular(24),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(",
		"            openLiteCopy.homeSummaryTitle,",
		"            style: const TextStyle(color: Colors.white70),",
		"          ),",
		"          const SizedBox(height: 12),",
		"          Wrap(",
		"            spacing: 12,",
		"            runSpacing: 12,",
		"            children: [",
		`              _HeroStat(label: '进行中', value: '${controller.totalOpenSheetCount}'),`,
		`              _HeroStat(label: '低库存', value: '${controller.totalLowStockSkuCount}'),`,
		`              _HeroStat(label: '差异项', value: '${controller.totalVarianceLineItemCount}'),`,
		"            ],",
		"          ),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _HeroStat extends StatelessWidget {",
		"  const _HeroStat({required this.label, required this.value});",
		"",
		"  final String label;",
		"  final String value;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),",
		"      decoration: BoxDecoration(",
		"        color: Colors.white.withValues(alpha: 0.14),",
		"        borderRadius: BorderRadius.circular(16),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(label, style: const TextStyle(color: Colors.white70)),",
		"          const SizedBox(height: 4),",
		"          Text(value, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700)),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _OverviewActions extends StatelessWidget {",
		"  const _OverviewActions({",
		"    required this.onCreateRecord,",
		"    required this.onViewAllRecords,",
		"  });",
		"",
		"  final VoidCallback onCreateRecord;",
		"  final VoidCallback onViewAllRecords;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Row(",
		"      children: [",
		"        Expanded(",
		"          child: FilledButton(",
		"            onPressed: onCreateRecord,",
		"            child: Text(openLiteCopy.createPrimaryActionLabel),",
		"          ),",
		"        ),",
		"        const SizedBox(width: 12),",
		"        Expanded(",
		"          child: OutlinedButton(",
		"            onPressed: onViewAllRecords,",
		"            child: Text(openLiteCopy.viewAllActionLabel),",
		"          ),",
		"        ),",
		"      ],",
		"    );",
		"  }",
		"}",
		"",
		"class _WarehouseSummaryCard extends StatelessWidget {",
		"  const _WarehouseSummaryCard({required this.warehouse, required this.summary});",
		"",
		"  final Warehouse warehouse;",
		"  final DashboardSummary? summary;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    final data = summary;",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(16),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            Text(warehouse.name, style: Theme.of(context).textTheme.titleMedium),",
		`            if ((warehouse.location ?? '').trim().isNotEmpty) ...[`,
		"              const SizedBox(height: 4),",
		`              Text('${openLiteCopy.warehouseLocationLabel}：${warehouse.location!.trim()}'),`,
		"            ],",
		"            const SizedBox(height: 12),",
		"            Wrap(",
		"              spacing: 12,",
		"              runSpacing: 12,",
		"              children: [",
		`                _SummaryStat(label: '进行中', value: '${data?.openSheetCount ?? 0}'),`,
		`                _SummaryStat(label: '低库存', value: '${data?.lowStockSkuCount ?? 0}'),`,
		`                _SummaryStat(label: '差异项', value: '${data?.varianceLineItemCount ?? 0}'),`,
		"              ],",
		"            ),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _SummaryStat extends StatelessWidget {",
		"  const _SummaryStat({required this.label, required this.value});",
		"",
		"  final String label;",
		"  final String value;",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Container(",
		"      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),",
		"      decoration: BoxDecoration(",
		"        color: Theme.of(context).colorScheme.surfaceContainerHighest,",
		"        borderRadius: BorderRadius.circular(16),",
		"      ),",
		"      child: Column(",
		"        crossAxisAlignment: CrossAxisAlignment.start,",
		"        children: [",
		"          Text(label),",
		"          const SizedBox(height: 4),",
		"          Text(value, style: Theme.of(context).textTheme.titleMedium),",
		"        ],",
		"      ),",
		"    );",
		"  }",
		"}",
		"",
		"class _OverviewEmptyState extends StatelessWidget {",
		"  const _OverviewEmptyState();",
		"",
		"  @override",
		"  Widget build(BuildContext context) {",
		"    return Card(",
		"      child: Padding(",
		"        padding: const EdgeInsets.all(24),",
		"        child: Column(",
		"          crossAxisAlignment: CrossAxisAlignment.start,",
		"          children: [",
		"            Text(openLiteCopy.homeEmptyTitle, style: Theme.of(context).textTheme.titleMedium),",
		"            const SizedBox(height: 8),",
		"            Text(openLiteCopy.homeEmptyDescription),",
		"          ],",
		"        ),",
		"      ),",
		"    );",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderProjectTaskTagHomeController 生成 project-task-tag profile 的 home_controller.dart。
func renderProjectTaskTagHomeController() string {
	return strings.Join([]string{
		"import 'package:flutter/foundation.dart' show ChangeNotifier, debugPrint;",
		"",
		"import '../models/dashboard_summary.dart';",
		"import '../models/project.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class HomeController extends ChangeNotifier {",
		"  HomeController({required RecordRepository repository}) : _repository = repository;",
		"",
		"  final RecordRepository _repository;",
		"",
		"  bool _isLoading = true;",
		"  List<Project> _projects = const [];",
		"  List<DashboardSummary> _summaries = const [];",
		"",
		"  bool get isLoading => _isLoading;",
		"  List<Project> get projects => List.unmodifiable(_projects);",
		"  List<DashboardSummary> get summaries => List.unmodifiable(_summaries);",
		"",
		"  Future<void> initialize() async {",
		"    await refresh();",
		"  }",
		"",
		"  Future<void> refresh() async {",
		"    _isLoading = true;",
		"    notifyListeners();",
		"    try {",
		"      final projects = await _repository.loadProjects();",
		"      final summaries = await _repository.loadSummaries();",
		"      _projects = projects;",
		"      _summaries = summaries;",
		"    } catch (error) {",
		"      debugPrint('Failed to refresh relation-rich home dashboard: $error');",
		"      _projects = const [];",
		"      _summaries = const [];",
		"    } finally {",
		"      _isLoading = false;",
		"      notifyListeners();",
		"    }",
		"  }",
		"",
		"  DashboardSummary? getSummaryForProject(String projectId) {",
		"    for (final summary in _summaries) {",
		"      if (summary.projectId == projectId) {",
		"        return summary;",
		"      }",
		"    }",
		"    return null;",
		"  }",
		"}",
	}, "\n") + "\n"
}

// renderInventoryHomeController 生成 inventory-sheet-line-item profile 的 home_controller.dart。
func renderInventoryHomeController() string {
	return strings.Join([]string{
		"import 'package:flutter/foundation.dart' show ChangeNotifier, debugPrint;",
		"",
		"import '../models/dashboard_summary.dart';",
		"import '../models/warehouse.dart';",
		"import '../repositories/record_repository.dart';",
		"",
		"class HomeController extends ChangeNotifier {",
		"  HomeController({required RecordRepository repository}) : _repository = repository;",
		"",
		"  final RecordRepository _repository;",
		"",
		"  bool _isLoading = true;",
		"  List<Warehouse> _warehouses = const [];",
		"  List<DashboardSummary> _summaries = const [];",
		"",
		"  bool get isLoading => _isLoading;",
		"  List<Warehouse> get warehouses => List.unmodifiable(_warehouses);",
		"  List<DashboardSummary> get summaries => List.unmodifiable(_summaries);",
		"  int get totalOpenSheetCount => _summaries.fold(0, (sum, summary) => sum + summary.openSheetCount);",
		"  int get totalLowStockSkuCount => _summaries.fold(0, (sum, summary) => sum + summary.lowStockSkuCount);",
		"  int get totalVarianceLineItemCount => _summaries.fold(0, (sum, summary) => sum + summary.varianceLineItemCount);",
		"",
		"  Future<void> initialize() async {",
		"    await refresh();",
		"  }",
		"",
		"  Future<void> refresh() async {",
		"    _isLoading = true;",
		"    notifyListeners();",
		"    try {",
		"      final warehouses = await _repository.loadWarehouses();",
		"      final summaries = await _repository.loadSummaries();",
		"      _warehouses = warehouses;",
		"      _summaries = summaries;",
		"    } catch (error) {",
		"      debugPrint('Failed to refresh inventory dashboard: $error');",
		"      _warehouses = const [];",
		"      _summaries = const [];",
		"    } finally {",
		"      _isLoading = false;",
		"      notifyListeners();",
		"    }",
		"  }",
		"",
		"  DashboardSummary? getSummaryForWarehouse(String warehouseId) {",
		"    for (final summary in _summaries) {",
		"      if (summary.warehouseId == warehouseId) {",
		"        return summary;",
		"      }",
		"    }",
		"    return null;",
		"  }",
		"}",
	}, "\n") + "\n"
}
