package emitter

import (
	"strings"

	appprepare "github.com/sipeed/oneappfactory/pkg/appfactory/prepare"
)

// RelationModelEmitResult 表示 relation-rich models emitter 的输出。
type RelationModelEmitResult struct {
	Files map[string]string
}

// EmitRelationModels 从 relation-rich DomainModel 确定性生成 lib/models 下的实体与摘要模型。
// 返回 (result, true) 表示成功；(zero, false) 表示当前 DomainModel 不在可 emit 范围内。
func EmitRelationModels(dm appprepare.DomainModel) (RelationModelEmitResult, bool) {
	switch identifyCopyProfile(dm) {
	case copyProfileProjectTaskTag:
		return RelationModelEmitResult{Files: renderProjectTaskTagRelationModels()}, true
	case copyProfileInventorySheetLineItem:
		return RelationModelEmitResult{Files: renderInventoryRelationModels()}, true
	default:
		return RelationModelEmitResult{}, false
	}
}

func renderProjectTaskTagRelationModels() map[string]string {
	return map[string]string{
		"lib/models/project.dart": strings.Join([]string{
			"class Project {",
			"  final String projectId;",
			"  final String title;",
			"  final ProjectStatus status;",
			"  final String? color;",
			"",
			"  Project({",
			"    required this.projectId,",
			"    required this.title,",
			"    required this.status,",
			"    this.color,",
			"  });",
			"",
			"  factory Project.fromJson(Map<String, dynamic> json) {",
			"    return Project(",
			"      projectId: json['project_id'] as String,",
			"      title: json['title'] as String,",
			"      status: ProjectStatus.values.firstWhere(",
			"        (status) => status.name == json['status'],",
			"        orElse: () => ProjectStatus.active,",
			"      ),",
			"      color: json['color'] as String?,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'project_id': projectId,",
			"      'title': title,",
			"      'status': status.name,",
			"      'color': color,",
			"    };",
			"  }",
			"}",
			"",
			"enum ProjectStatus {",
			"  active,",
			"  paused,",
			"  done",
			"}",
		}, "\n") + "\n",
		"lib/models/task.dart": strings.Join([]string{
			"class Task {",
			"  final String taskId;",
			"  final String projectId;",
			"  final String title;",
			"  final TaskStatus status;",
			"  final DateTime? dueOn;",
			"  final String? note;",
			"",
			"  Task({",
			"    required this.taskId,",
			"    required this.projectId,",
			"    required this.title,",
			"    required this.status,",
			"    this.dueOn,",
			"    this.note,",
			"  });",
			"",
			"  factory Task.fromJson(Map<String, dynamic> json) {",
			"    return Task(",
			"      taskId: json['task_id'] as String,",
			"      projectId: json['project_id'] as String,",
			"      title: json['title'] as String,",
			"      status: TaskStatus.values.firstWhere(",
			"        (status) => status.name == json['status'],",
			"        orElse: () => TaskStatus.todo,",
			"      ),",
			"      dueOn: json['due_on'] != null ? DateTime.parse(json['due_on'] as String) : null,",
			"      note: json['note'] as String?,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'task_id': taskId,",
			"      'project_id': projectId,",
			"      'title': title,",
			"      'status': status.name,",
			"      'due_on': dueOn?.toIso8601String(),",
			"      'note': note,",
			"    };",
			"  }",
			"}",
			"",
			"enum TaskStatus {",
			"  todo,",
			"  doing,",
			"  done",
			"}",
		}, "\n") + "\n",
		"lib/models/tag.dart": strings.Join([]string{
			"class Tag {",
			"  final String tagId;",
			"  final String name;",
			"  final String? color;",
			"",
			"  Tag({",
			"    required this.tagId,",
			"    required this.name,",
			"    this.color,",
			"  });",
			"",
			"  factory Tag.fromJson(Map<String, dynamic> json) {",
			"    return Tag(",
			"      tagId: json['tag_id'] as String,",
			"      name: json['name'] as String,",
			"      color: json['color'] as String?,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'tag_id': tagId,",
			"      'name': name,",
			"      'color': color,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
		"lib/models/task_tag_link.dart": strings.Join([]string{
			"class TaskTagLink {",
			"  final String linkId;",
			"  final String taskId;",
			"  final String tagId;",
			"",
			"  TaskTagLink({",
			"    required this.linkId,",
			"    required this.taskId,",
			"    required this.tagId,",
			"  });",
			"",
			"  factory TaskTagLink.fromJson(Map<String, dynamic> json) {",
			"    return TaskTagLink(",
			"      linkId: json['link_id'] as String,",
			"      taskId: json['task_id'] as String,",
			"      tagId: json['tag_id'] as String,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'link_id': linkId,",
			"      'task_id': taskId,",
			"      'tag_id': tagId,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
		"lib/models/dashboard_summary.dart": strings.Join([]string{
			"class DashboardSummary {",
			"  final String projectId;",
			"  final int openTaskCount;",
			"  final int doneTaskCount;",
			"  final int taggedTaskCount;",
			"",
			"  const DashboardSummary({",
			"    required this.projectId,",
			"    required this.openTaskCount,",
			"    required this.doneTaskCount,",
			"    required this.taggedTaskCount,",
			"  });",
			"",
			"  factory DashboardSummary.fromJson(Map<String, dynamic> json) {",
			"    return DashboardSummary(",
			"      projectId: json['project_id'] as String,",
			"      openTaskCount: json['open_task_count'] as int,",
			"      doneTaskCount: json['done_task_count'] as int,",
			"      taggedTaskCount: json['tagged_task_count'] as int,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'project_id': projectId,",
			"      'open_task_count': openTaskCount,",
			"      'done_task_count': doneTaskCount,",
			"      'tagged_task_count': taggedTaskCount,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
	}
}

func renderInventoryRelationModels() map[string]string {
	return map[string]string{
		"lib/models/inventory_sheet.dart": strings.Join([]string{
			"class InventorySheet {",
			"  final String sheetId;",
			"  final String warehouseId;",
			"  final InventorySheetStatus status;",
			"  final DateTime countedOn;",
			"  final String? note;",
			"",
			"  InventorySheet({",
			"    required this.sheetId,",
			"    required this.warehouseId,",
			"    required this.status,",
			"    required this.countedOn,",
			"    this.note,",
			"  });",
			"",
			"  factory InventorySheet.fromJson(Map<String, dynamic> json) {",
			"    return InventorySheet(",
			"      sheetId: json['sheet_id'] as String,",
			"      warehouseId: json['warehouse_id'] as String,",
			"      status: InventorySheetStatus.values.firstWhere(",
			"        (status) => status.name == json['status'],",
			"        orElse: () => InventorySheetStatus.draft,",
			"      ),",
			"      countedOn: DateTime.parse(json['counted_on'] as String),",
			"      note: json['note'] as String?,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'sheet_id': sheetId,",
			"      'warehouse_id': warehouseId,",
			"      'status': status.name,",
			"      'counted_on': countedOn.toIso8601String(),",
			"      'note': note,",
			"    };",
			"  }",
			"}",
			"",
			"enum InventorySheetStatus {",
			"  draft,",
			"  checking,",
			"  closed",
			"}",
		}, "\n") + "\n",
		"lib/models/line_item.dart": strings.Join([]string{
			"class LineItem {",
			"  final String lineItemId;",
			"  final String sheetId;",
			"  final String skuId;",
			"  final int expectedQty;",
			"  final int countedQty;",
			"  final int varianceQty;",
			"",
			"  LineItem({",
			"    required this.lineItemId,",
			"    required this.sheetId,",
			"    required this.skuId,",
			"    required this.expectedQty,",
			"    required this.countedQty,",
			"    required this.varianceQty,",
			"  });",
			"",
			"  factory LineItem.fromJson(Map<String, dynamic> json) {",
			"    return LineItem(",
			"      lineItemId: json['line_item_id'] as String,",
			"      sheetId: json['sheet_id'] as String,",
			"      skuId: json['sku_id'] as String,",
			"      expectedQty: json['expected_qty'] as int,",
			"      countedQty: json['counted_qty'] as int,",
			"      varianceQty: json['variance_qty'] as int,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'line_item_id': lineItemId,",
			"      'sheet_id': sheetId,",
			"      'sku_id': skuId,",
			"      'expected_qty': expectedQty,",
			"      'counted_qty': countedQty,",
			"      'variance_qty': varianceQty,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
		"lib/models/sku.dart": strings.Join([]string{
			"class Sku {",
			"  final String skuId;",
			"  final String name;",
			"  final String category;",
			"  final int reorderThreshold;",
			"",
			"  Sku({",
			"    required this.skuId,",
			"    required this.name,",
			"    required this.category,",
			"    required this.reorderThreshold,",
			"  });",
			"",
			"  factory Sku.fromJson(Map<String, dynamic> json) {",
			"    return Sku(",
			"      skuId: json['sku_id'] as String,",
			"      name: json['name'] as String,",
			"      category: json['category'] as String,",
			"      reorderThreshold: json['reorder_threshold'] as int,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'sku_id': skuId,",
			"      'name': name,",
			"      'category': category,",
			"      'reorder_threshold': reorderThreshold,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
		"lib/models/warehouse.dart": strings.Join([]string{
			"class Warehouse {",
			"  final String warehouseId;",
			"  final String name;",
			"  final String? location;",
			"",
			"  Warehouse({",
			"    required this.warehouseId,",
			"    required this.name,",
			"    this.location,",
			"  });",
			"",
			"  factory Warehouse.fromJson(Map<String, dynamic> json) {",
			"    return Warehouse(",
			"      warehouseId: json['warehouse_id'] as String,",
			"      name: json['name'] as String,",
			"      location: json['location'] as String?,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'warehouse_id': warehouseId,",
			"      'name': name,",
			"      'location': location,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
		"lib/models/dashboard_summary.dart": strings.Join([]string{
			"class DashboardSummary {",
			"  final String warehouseId;",
			"  final int openSheetCount;",
			"  final int lowStockSkuCount;",
			"  final int varianceLineItemCount;",
			"",
			"  const DashboardSummary({",
			"    required this.warehouseId,",
			"    required this.openSheetCount,",
			"    required this.lowStockSkuCount,",
			"    required this.varianceLineItemCount,",
			"  });",
			"",
			"  factory DashboardSummary.fromJson(Map<String, dynamic> json) {",
			"    return DashboardSummary(",
			"      warehouseId: json['warehouse_id'] as String,",
			"      openSheetCount: json['open_sheet_count'] as int,",
			"      lowStockSkuCount: json['low_stock_sku_count'] as int,",
			"      varianceLineItemCount: json['variance_line_item_count'] as int,",
			"    );",
			"  }",
			"",
			"  Map<String, dynamic> toJson() {",
			"    return {",
			"      'warehouse_id': warehouseId,",
			"      'open_sheet_count': openSheetCount,",
			"      'low_stock_sku_count': lowStockSkuCount,",
			"      'variance_line_item_count': varianceLineItemCount,",
			"    };",
			"  }",
			"}",
		}, "\n") + "\n",
	}
}
