#!/bin/sh
set -e

ONEAPPFACTORY_HOME="${ONEAPPFACTORY_HOME:-${HOME}/.appfactory}"
ONEAPPFACTORY_CONFIG="${ONEAPPFACTORY_CONFIG:-${ONEAPPFACTORY_HOME}/config.json}"
ONEAPPFACTORY_PORT="${ONEAPPFACTORY_PORT:-18800}"
export ONEAPPFACTORY_HOME ONEAPPFACTORY_CONFIG

mkdir -p "$ONEAPPFACTORY_HOME"

if [ "$#" -gt 0 ]; then
    exec "$@"
fi

exec oneappfactory-launcher -public -no-browser -port "$ONEAPPFACTORY_PORT" "$ONEAPPFACTORY_CONFIG"
