// PicoClaw - Ultra-lightweight personal AI agent
// License: MIT
//
// Copyright (c) 2026 PicoClaw contributors

package agent

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/sipeed/picoclaw/pkg/logger"
	"github.com/sipeed/picoclaw/pkg/providers"
)

// StreamConversationKeys 描述流式语音在短期 session 与 owner 级 memory
// 之间的双键关系。SessionKey 始终承担当前语音会话 transcript，
// MemoryKey 则在可解析 owner 时承担读写 owner 级摘要与归档。
type StreamConversationKeys struct {
	SessionKey string
	MemoryKey  string
}

func normalizeStreamConversationKeys(keys StreamConversationKeys) StreamConversationKeys {
	keys.SessionKey = strings.TrimSpace(keys.SessionKey)
	keys.MemoryKey = strings.TrimSpace(keys.MemoryKey)

	if keys.SessionKey == "" {
		keys.SessionKey = keys.MemoryKey
		keys.MemoryKey = ""
		return keys
	}

	if keys.MemoryKey == "" || keys.MemoryKey == keys.SessionKey {
		keys.MemoryKey = ""
	}

	return keys
}

func composeStreamSummary(sessionSummary, memorySummary string) string {
	sessionSummary = strings.TrimSpace(sessionSummary)
	memorySummary = strings.TrimSpace(memorySummary)

	switch {
	case sessionSummary == "" && memorySummary == "":
		return ""
	case sessionSummary == "":
		return "OWNER_MEMORY_SUMMARY:\n" + memorySummary
	case memorySummary == "" || memorySummary == sessionSummary:
		return sessionSummary
	default:
		return "VOICE_SESSION_SUMMARY:\n" + sessionSummary + "\n\nOWNER_MEMORY_SUMMARY:\n" + memorySummary
	}
}

func addMessageToStreamKeys(agentInst *AgentInstance, keys StreamConversationKeys, role, content string) {
	agentInst.Sessions.AddMessage(keys.SessionKey, role, content)
	if keys.MemoryKey != "" {
		agentInst.Sessions.AddMessage(keys.MemoryKey, role, content)
	}
}

func (al *AgentLoop) maybeSummarizeStreamKeys(
	agentInst *AgentInstance,
	keys StreamConversationKeys,
	channel, chatID string,
) {
	al.maybeSummarize(agentInst, keys.SessionKey, channel, chatID)
	if keys.MemoryKey != "" {
		al.maybeSummarize(agentInst, keys.MemoryKey, channel, chatID)
	}
}

// RunStreamAgentLoop runs a streaming LLM agent loop for voice input.
// Text tokens are delivered via onToken as they are generated by the LLM.
// Tool calls are executed transparently between iterations; the loop
// re-prompts with results and continues until no more tool calls are issued
// or MaxIterations is reached.
// The full exchange is persisted to session memory on completion.
func (al *AgentLoop) RunStreamAgentLoop(
	ctx context.Context,
	sessionKey, userText, channel, chatID string,
	onToken func(string),
) error {
	return al.RunStreamAgentLoopWithKeys(
		ctx,
		StreamConversationKeys{SessionKey: sessionKey},
		userText,
		channel,
		chatID,
		onToken,
	)
}

// RunStreamAgentLoopWithKeys 允许语音路径同时维护短期 session transcript 和
// owner 级长期摘要归档。当前短期上下文仍以 SessionKey 为主，MemoryKey 仅承担
// owner 级摘要与归档的并行持久化。
func (al *AgentLoop) RunStreamAgentLoopWithKeys(
	ctx context.Context,
	keys StreamConversationKeys,
	userText, channel, chatID string,
	onToken func(string),
) error {
	keys = normalizeStreamConversationKeys(keys)
	if keys.SessionKey == "" {
		return fmt.Errorf("stream session key is required")
	}

	agentInst := al.registry.GetDefaultAgent()
	if agentInst == nil {
		return fmt.Errorf("no default agent available")
	}

	sp, streamCapable := agentInst.Provider.(providers.StreamingProvider)
	if !streamCapable {
		logger.WarnCF("voice-stream", "Provider does not implement StreamingProvider, falling back to Chat",
			map[string]any{"provider": fmt.Sprintf("%T", agentInst.Provider)})
	}

	start := time.Now()

	history := agentInst.Sessions.GetHistory(keys.SessionKey)
	summary := composeStreamSummary(
		agentInst.Sessions.GetSummary(keys.SessionKey),
		agentInst.Sessions.GetSummary(keys.MemoryKey),
	)
	messages := agentInst.ContextBuilder.BuildMessages(
		history, summary, userText, nil, channel, chatID, "", "",
	)

	addMessageToStreamKeys(agentInst, keys, "user", userText)

	llmOpts := map[string]any{
		"max_tokens":       agentInst.MaxTokens,
		"temperature":      agentInst.Temperature,
		"prompt_cache_key": agentInst.ID,
	}

	var finalContent string
	for iteration := 0; iteration < agentInst.MaxIterations; iteration++ {
		toolDefs := agentInst.Tools.ToProviderDefs()

		var resp *providers.LLMResponse
		var err error
		tokenObserved := false

		if streamCapable {
			// [KKROID FORK] onChunk 已经是增量 delta，直接透传给 onToken
			var chunkCb func(string)
			if onToken != nil {
				chunkCb = func(delta string) {
					tokenObserved = true
					onToken(delta)
				}
			}
			resp, err = sp.ChatStream(ctx, messages, toolDefs, agentInst.Model, llmOpts, chunkCb)
		} else {
			resp, err = agentInst.Provider.Chat(ctx, messages, toolDefs, agentInst.Model, llmOpts)
		}
		if err != nil {
			return fmt.Errorf("stream error (iteration %d): %w", iteration+1, err)
		}
		if resp == nil {
			resp = &providers.LLMResponse{}
		}
		if !tokenObserved && onToken != nil && strings.TrimSpace(resp.Content) != "" {
			onToken(resp.Content)
		}
		finalContent = resp.Content

		if len(resp.ToolCalls) == 0 {
			break
		}

		// Normalize tool calls so Name/Arguments map are always populated.
		normalizedCalls := make([]providers.ToolCall, 0, len(resp.ToolCalls))
		for _, tc := range resp.ToolCalls {
			normalizedCalls = append(normalizedCalls, providers.NormalizeToolCall(tc))
		}

		// Append assistant message with tool calls.
		assistantMsg := providers.Message{
			Role:    "assistant",
			Content: resp.Content,
		}
		for _, tc := range normalizedCalls {
			assistantMsg.ToolCalls = append(assistantMsg.ToolCalls, tc)
		}
		messages = append(messages, assistantMsg)

		// Execute each tool and add results to context.
		for _, tc := range normalizedCalls {
			result := agentInst.Tools.ExecuteWithContext(ctx, tc.Name, tc.Arguments, channel, chatID, nil)
			contentForLLM := result.ForLLM
			if contentForLLM == "" && result.Err != nil {
				contentForLLM = result.Err.Error()
			}
			messages = agentInst.ContextBuilder.AddToolResult(
				messages, tc.ID, tc.Name, contentForLLM,
			)
			logger.DebugCF("voice-stream", "Tool executed",
				map[string]any{"tool": tc.Name, "result_len": len(contentForLLM)})
		}
	}

	addMessageToStreamKeys(agentInst, keys, "assistant", finalContent)
	if err := agentInst.Sessions.Save(keys.SessionKey); err != nil {
		logger.WarnCF("voice-stream", "Failed to save session",
			map[string]any{"session_key": keys.SessionKey, "error": err.Error()})
	}
	if keys.MemoryKey != "" {
		if err := agentInst.Sessions.Save(keys.MemoryKey); err != nil {
			logger.WarnCF("voice-stream", "Failed to save owner memory",
				map[string]any{"memory_key": keys.MemoryKey, "error": err.Error()})
		}
	}
	al.maybeSummarizeStreamKeys(agentInst, keys, channel, chatID)

	logger.InfoCF("voice-stream", "Stream completed",
		map[string]any{
			"session_key": keys.SessionKey,
			"memory_key":  keys.MemoryKey,
			"latency_ms":  time.Since(start).Milliseconds(),
			"content_len": len(finalContent),
		})

	return nil
}
